/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2015-4-24:  0h:19m
**
*/

/* ATSextcode_beg() */
// COMMENT_line

var Flyer = function(){
    this.dom = null;
    this.isLive = true;
    this.isMove = false;
    this.moveId = null;
    this.isSend = false;
    this.nowBullet = 0;
    this.Lives = 3;
    this.init();
}
// COMMENT_line

Flyer.prototype = {
    gamePanel : null,
    gameWidth : 0,
    gameHeight : 0,
    movepx : 10,
    movesp : 30,
    bulletLevel : 1,
    maxBullet : 12,
    keyCodeAndDirection : {
        37 : "left",
        38 : "up",
        39 : "right",
        40 : "down"
    },
    init : function(){
        this.dom = document.createElement('div');
        this.dom.className = 'flyer';
    }
}
/* ATSextcode_end() */

/* ATSextcode_beg() */
// COMMENT_line

function
flyerSetPosition(flyer,gamePanel,width,height){
    var flyer = flyer;
    var gamePanel = gamePanel;
    gamePanel.appendChild(flyer.dom);
    flyer.dom.style.left = (width - flyer.dom.clientWidth) / 2 + 'px';
    flyer.dom.style.top = height - flyer.dom.clientHeight + 'px';
    flyer.gameWidth = width;
    flyer.gameHeight = height;
}
/* ATSextcode_end() */
// dynloadflag_init
var _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_flyer_056_dats__dynloadflag = 0;

function
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_flyer_056_dats__dynload()
{
//
// knd = 0
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_flyer_056_dats__dynloadflag(11))
  if(ATSCKiseqz(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_flyer_056_dats__dynloadflag)) {
    _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_flyer_056_dats__dynloadflag = 1 ; // flag is set
  } // endif
  return/*_void*/;
} // end-of-function


function
mygame_flyer_initize()
{
//
// knd = 0
//
  _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_flyer_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ****** ****** */

/* end-of-compilation-unit */
