/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2015-4-27: 12h:21m
**
*/

var statmp0

var statmp1

function
init_0()
{
//
// knd = 0
//
  // __patsflab_init_0
  player_init();
  return/*_void*/;
} // end-of-function


function
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get()
{
//
// knd = 0
  var tmpret3
  var tmp4
  var tmp5
  var tmp7
  var tmp8
  var tmp10
//
  // __patsflab_player_get
  tmp5 = ats2jspre_ref_get_elt(statmp0);
  tmp4 = ats2jspre_gt_int0_int0(tmp5, 0);
  if(tmp4) {
    tmp8 = ats2jspre_ref_get_elt(statmp0);
    tmp7 = ats2jspre_sub_int0_int0(tmp8, 1);
    ats2jspre_ref_set_elt(statmp0, tmp7);
    tmp10 = ats2jspre_ref_get_elt(statmp0);
    update_lives(tmp10);
    tmpret3 = [1];
  } else {
    gameover();
    tmpret3 = null;
  } // endif
  return tmpret3;
} // end-of-function


function
player_keyPress()
{
//
// knd = 0
  var tmp15
  var tmp16
  var tmp17
  var tmp19
  var tmp20
  var tmp22
  var tmp23
  var tmp24
  var tmp25
  var tmp26
//
  // __patsflab_player_keyPress
  tmp16 = check_key(37);
  tmp15 = ats2jspre_eq_int0_int0(tmp16, 1);
  if(tmp15) {
    tmp17 = ats2jspre_neg_int0(20);
    player_move(tmp17, 0);
  } else {
    // ATSINSmove_void
  } // endif
  tmp20 = check_key(39);
  tmp19 = ats2jspre_eq_int0_int0(tmp20, 1);
  if(tmp19) {
    player_move(20, 0);
  } else {
    // ATSINSmove_void
  } // endif
  tmp23 = check_key(38);
  tmp22 = ats2jspre_eq_int0_int0(tmp23, 1);
  if(tmp22) {
    player_move(0, 20);
  } else {
    // ATSINSmove_void
  } // endif
  tmp25 = check_key(40);
  tmp24 = ats2jspre_eq_int0_int0(tmp25, 1);
  if(tmp24) {
    tmp26 = ats2jspre_neg_int0(20);
    player_move(0, tmp26);
  } else {
    // ATSINSmove_void
  } // endif
  return/*_void*/;
} // end-of-function


function
player_move(arg0, arg1)
{
//
// knd = 0
  var tmp28
  var tmp29
  var tmp30
  var tmp31
  var tmp32
  var tmp33
  var tmp34
  var tmp35
  var tmp36
  var tmp37
  var tmp38
  var tmp39
  var tmp40
  var tmp41
  var tmp42
  var tmp43
  var tmp44
//
  // __patsflab_player_move
  tmp28 = ats2jspre_eq_int0_int0(arg0, 0);
  if(tmp28) {
    tmp29 = player_getPosition_Y();
    tmp32 = ats2jspre_add_int0_int0(tmp29, arg1);
    tmp31 = ats2jspre_gt_int0_int0(tmp32, 500);
    if(tmp31) {
      tmp30 = true;
    } else {
      tmp33 = ats2jspre_add_int0_int0(tmp29, arg1);
      tmp34 = ats2jspre_div_int1_int1(18, 2);
      tmp30 = ats2jspre_lte_int0_int0(tmp33, tmp34);
    } // endif
    if(tmp30) {
      // ATSINSmove_void
    } else {
      tmp35 = ats2jspre_add_int0_int0(tmp29, arg1);
      player_setPosition_Y(tmp35);
    } // endif
  } else {
    tmp36 = player_getPosition_X();
    tmp39 = ats2jspre_add_int0_int0(tmp36, arg0);
    tmp41 = ats2jspre_div_int1_int1(18, 2);
    tmp40 = ats2jspre_sub_int1_int1(400, tmp41);
    tmp38 = ats2jspre_gte_int0_int0(tmp39, tmp40);
    if(tmp38) {
      tmp37 = true;
    } else {
      tmp42 = ats2jspre_add_int0_int0(tmp36, arg0);
      tmp43 = ats2jspre_div_int1_int1(18, 2);
      tmp37 = ats2jspre_lt_int0_int0(tmp42, tmp43);
    } // endif
    if(tmp37) {
      // ATSINSmove_void
    } else {
      tmp44 = ats2jspre_add_int0_int0(tmp36, arg0);
      player_setPosition_X(tmp44);
    } // endif
  } // endif
  return/*_void*/;
} // end-of-function


function
game_tick(arg0)
{
//
// knd = 0
//
  // __patsflab_game_tick
  player_update(arg0);
  return/*_void*/;
} // end-of-function


function
player_update(arg0)
{
//
// knd = 0
//
  // __patsflab_player_update
  player_keyPress();
  return/*_void*/;
} // end-of-function

// dynloadflag_init
var _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag = 0;

function
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynload()
{
//
// knd = 0
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag(100))
  if(ATSCKiseqz(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag)) {
    _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag = 1 ; // flag is set
    statmp0 = ats2jspre_ref(3);
    statmp1 = ats2jspre_ref(0);
    init_0();
  } // endif
  return/*_void*/;
} // end-of-function


function
my_dynload()
{
//
// knd = 0
//
  _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
// COMMENT_line

function
ATS_start()
{
  var _ = my_dynload()
}
// COMMENT_line

/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
