/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-4-29: 22h:58m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
/cs/coursedata/cs520/ATS2-017/libc/SATS/math.sats: 1380(line=35, offs=1) -- 1417(line=37, offs=3)
*/

#include "libc/CATS/math.cats"
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/list.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 357(line=27, offs=1) -- 396(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 423(line=32, offs=1) -- 455(line=32, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 482(line=36, offs=1) -- 512(line=36, offs=31)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/print.sats: 189(line=14, offs=1) -- 218(line=14, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 513(line=37, offs=1) -- 545(line=37, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/filebas.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 572(line=41, offs=1) -- 601(line=41, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/list.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/option.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 359(line=27, offs=1) -- 398(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 425(line=32, offs=1) -- 457(line=32, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 484(line=36, offs=1) -- 515(line=36, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/option.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 359(line=27, offs=1) -- 398(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 425(line=32, offs=1) -- 457(line=33, offs=25)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 461(line=35, offs=1) -- 491(line=35, offs=31)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/print.sats: 189(line=14, offs=1) -- 218(line=14, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 516(line=39, offs=1) -- 547(line=39, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/reference.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSmath.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSdate.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSarray.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSglobal.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(ats2jspre_ref)
ATSdyncst_mac(ats2jspre_ref_set_elt)
ATSdyncst_mac(player_init)
ATSdyncst_mac(ats2jspre_gt_int0_int0)
ATSdyncst_mac(ats2jspre_ref_get_elt)
ATSdyncst_mac(ats2jspre_sub_int0_int0)
ATSdyncst_mac(update_lives)
ATSdyncst_mac(gameover)
ATSdyncst_mac(ats2jspre_lte_int0_int0)
ATSdyncst_mac(ats2jspre_add_int0_int0)
ATSdyncst_mac(ats2jspre_eq_int0_int0)
ATSdyncst_mac(check_key)
ATSdyncst_mac(player_move)
ATSdyncst_mac(ats2jspre_neg_double)
ATSdyncst_mac(ats2jspre_eq_double_double)
ATSdyncst_mac(player_getPosition_Y)
ATSdyncst_mac(ats2jspre_gt_double_double)
ATSdyncst_mac(ats2jspre_add_double_double)
ATSdyncst_mac(ats2jspre_lte_double_double)
ATSdyncst_mac(ats2jspre_div_double_double)
ATSdyncst_mac(player_setPosition_Y)
ATSdyncst_mac(player_getPosition_X)
ATSdyncst_mac(ats2jspre_sub_double_double)
ATSdyncst_mac(ats2jspre_div_double_int)
ATSdyncst_mac(ats2jspre_lt_double_double)
ATSdyncst_mac(player_setPosition_X)
ATSdyncst_mac(enemy_update)
ATSdyncst_mac(score_update)
ATSdyncst_mac(player_update)
ATSdyncst_mac(player_keyPress)
ATSdyncst_mac(enemy_get)
ATSdyncst_mac(create_enemy)
ATSdyncst_mac(set_enemy_animation)
ATSdyncst_mac(enemy_getPosition_X)
ATSdyncst_mac(enemy_getPosition_Y)
ATSdyncst_mac(calc_speed_x)
ATSdyncst_mac(ats2jspre_mul_double_double)
ATSdyncst_mac(enemy_move)
ATSdyncst_mac(player_crash)
ATSdyncst_mac(enemy_remove)
ATSdyncst_mac(player_get)
ATSdyncst_mac(enemy_setPosition)
ATSdyncst_mac(enemy_check_crash)
ATSdyncst_mac(enemy_check_bound)
ATSdyncst_mac(panel_remove)
ATSdyncst_mac(setTimeout_cloref)
ATSdyncst_mac(calc_dist)
ATSdyncst_mac(crash_report)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatmpdec(statmp0, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp1, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp2, atstkind_type(atstype_ptrk)) ;
#if(0)
ATSextern()
atsvoid_t0ype
init() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
player_get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
enemy_get(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
enemy_move_get(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_keyPress() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_move(atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
game_tick(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_update(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
enemy_update(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
set_enemy_animation(gameobject) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
__patsfun_10(gameobject) ;

#if(0)
ATSextern()
atsvoid_t0ype
player_crash(gameobject) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
enemy_move(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
__patsfun_13(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_funptr) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_crash(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_bound(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
cloref_app(atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSclosurerize_beg(__patsfun_10, (gameobject), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
gameobject env0 ;
} __patsfun_10__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_10__cfun
(
__patsfun_10__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_10(p_cenv->env0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_10__closureinit
(
__patsfun_10__closure_t0ype *p_cenv, gameobject env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_10__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_10__closurerize
(
gameobject env0
)
{
return __patsfun_10__closureinit(ATS_MALLOC(sizeof(__patsfun_10__closure_t0ype)), env0) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(__patsfun_13, (gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_funptr), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
gameobject env0 ;
atstkind_t0ype(atstype_double) env1 ;
atstkind_t0ype(atstype_double) env2 ;
atstype_funptr env3 ;
} __patsfun_13__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_13__cfun
(
__patsfun_13__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_13(p_cenv->env0, p_cenv->env1, p_cenv->env2, p_cenv->env3)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_13__closureinit
(
__patsfun_13__closure_t0ype *p_cenv, gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->env2 = env2 ;
p_cenv->env3 = env3 ;
p_cenv->cfun = __patsfun_13__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_13__closurerize
(
gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3
)
{
return __patsfun_13__closureinit(ATS_MALLOC(sizeof(__patsfun_13__closure_t0ype)), env0, env1, env2, env3) ;
} /* end of [closurerize] */
ATSclosurerize_end()
/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 460(line=27, offs=17) -- 556(line=32, offs=4)
*/
/*
local: 
global: init$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
init()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret3) ;
// ATStmpdec_void(tmp4) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 456(line=27, offs=13) -- 556(line=32, offs=4)
*/
ATSINSflab(__patsflab_init):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 474(line=28, offs=3) -- 556(line=32, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 510(line=30, offs=14) -- 523(line=30, offs=27)
*/
ATSINSmove_void(tmp4, ats2jspre_ref_set_elt(statmp0, ATSPMVi0nt(3))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 538(line=31, offs=14) -- 551(line=31, offs=27)
*/
ATSINSmove_void(tmpret3, player_init()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 474(line=28, offs=3) -- 556(line=32, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret3) ;
} /* end of [init] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 582(line=34, offs=23) -- 806(line=44, offs=8)
*/
/*
local: 
global: player_get$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
player_get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstype_boxed) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp8) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp11) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp13) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 572(line=34, offs=13) -- 806(line=44, offs=8)
*/
ATSINSflab(__patsflab_player_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 596(line=35, offs=8) -- 604(line=35, offs=16)
*/
ATSINSmove(tmp7, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 596(line=35, offs=8) -- 608(line=35, offs=20)
*/
ATSINSmove(tmp6, ats2jspre_gt_int0_int0(tmp7, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 593(line=35, offs=5) -- 806(line=44, offs=8)
*/
ATSif(
tmp6
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 614(line=35, offs=26) -- 735(line=40, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 647(line=36, offs=29) -- 655(line=36, offs=37)
*/
ATSINSmove(tmp10, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 647(line=36, offs=29) -- 659(line=36, offs=41)
*/
ATSINSmove(tmp9, ats2jspre_sub_int0_int0(tmp10, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 635(line=36, offs=17) -- 659(line=36, offs=41)
*/
ATSINSmove_void(tmp8, ats2jspre_ref_set_elt(statmp0, tmp9)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 691(line=37, offs=31) -- 699(line=37, offs=39)
*/
ATSINSmove(tmp12, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 678(line=37, offs=18) -- 700(line=37, offs=40)
*/
ATSINSmove_void(tmp11, update_lives(tmp12)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 719(line=39, offs=9) -- 726(line=39, offs=16)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret5, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret5, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret5, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 614(line=35, offs=26) -- 735(line=40, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 741(line=40, offs=14) -- 806(line=44, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 763(line=41, offs=18) -- 773(line=41, offs=28)
*/
ATSINSmove_void(tmp13, gameover()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 791(line=43, offs=9) -- 797(line=43, offs=15)
*/

ATSINSmove_nil(tmpret5) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 741(line=40, offs=14) -- 806(line=44, offs=8)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret5) ;
} /* end of [player_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 831(line=46, offs=22) -- 1041(line=55, offs=6)
*/
/*
local: 
global: enemy_get$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
enemy_get(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14, atstype_boxed) ;
// ATStmpdec_void(tmp15) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp20) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp22, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 822(line=46, offs=13) -- 1041(line=55, offs=6)
*/
ATSINSflab(__patsflab_enemy_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 838(line=46, offs=29) -- 1041(line=55, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 872(line=47, offs=30) -- 884(line=47, offs=42)
*/
ATSINSmove(tmp17, ats2jspre_ref_get_elt(statmp1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 872(line=47, offs=30) -- 889(line=47, offs=47)
*/
ATSINSmove(tmp16, ats2jspre_sub_int0_int0(tmp17, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 856(line=47, offs=14) -- 889(line=47, offs=47)
*/
ATSINSmove_void(tmp15, ats2jspre_ref_set_elt(statmp1, tmp16)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 904(line=49, offs=8) -- 916(line=49, offs=20)
*/
ATSINSmove(tmp19, ats2jspre_ref_get_elt(statmp1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 904(line=49, offs=8) -- 921(line=49, offs=25)
*/
ATSINSmove(tmp18, ats2jspre_lte_int0_int0(tmp19, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 901(line=49, offs=5) -- 1034(line=54, offs=20)
*/
ATSif(
tmp18
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 927(line=49, offs=31) -- 1022(line=54, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 965(line=51, offs=32) -- 977(line=51, offs=44)
*/
ATSINSmove(tmp22, ats2jspre_ref_get_elt(statmp1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 965(line=51, offs=32) -- 990(line=51, offs=57)
*/
ATSINSmove(tmp21, ats2jspre_add_int0_int0(tmp22, ATSPMVintrep(100))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 949(line=51, offs=16) -- 990(line=51, offs=57)
*/
ATSINSmove_void(tmp20, ats2jspre_ref_set_elt(statmp1, tmp21)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1006(line=53, offs=7) -- 1013(line=53, offs=14)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret14, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret14, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret14, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 927(line=49, offs=31) -- 1022(line=54, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1028(line=54, offs=14) -- 1034(line=54, offs=20)
*/

ATSINSmove_nil(tmpret14) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 838(line=46, offs=29) -- 1041(line=55, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret14) ;
} /* end of [enemy_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1085(line=58, offs=27) -- 1263(line=66, offs=6)
*/
/*
local: 
global: enemy_move_get$3$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
enemy_move_get(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret23, atstype_boxed) ;
// ATStmpdec_void(tmp24) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp27, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp29) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1071(line=58, offs=13) -- 1263(line=66, offs=6)
*/
ATSINSflab(__patsflab_enemy_move_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1092(line=58, offs=34) -- 1263(line=66, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1122(line=59, offs=26) -- 1130(line=59, offs=34)
*/
ATSINSmove(tmp26, ats2jspre_ref_get_elt(statmp2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1122(line=59, offs=26) -- 1135(line=59, offs=39)
*/
ATSINSmove(tmp25, ats2jspre_sub_int0_int0(tmp26, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1110(line=59, offs=14) -- 1135(line=59, offs=39)
*/
ATSINSmove_void(tmp24, ats2jspre_ref_set_elt(statmp2, tmp25)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1150(line=61, offs=8) -- 1158(line=61, offs=16)
*/
ATSINSmove(tmp28, ats2jspre_ref_get_elt(statmp2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1150(line=61, offs=8) -- 1163(line=61, offs=21)
*/
ATSINSmove(tmp27, ats2jspre_lte_int0_int0(tmp28, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1147(line=61, offs=5) -- 1256(line=65, offs=20)
*/
ATSif(
tmp27
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1169(line=61, offs=27) -- 1244(line=65, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1201(line=62, offs=28) -- 1209(line=62, offs=36)
*/
ATSINSmove(tmp31, ats2jspre_ref_get_elt(statmp2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1201(line=62, offs=28) -- 1214(line=62, offs=41)
*/
ATSINSmove(tmp30, ats2jspre_add_int0_int0(tmp31, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1189(line=62, offs=16) -- 1214(line=62, offs=41)
*/
ATSINSmove_void(tmp29, ats2jspre_ref_set_elt(statmp2, tmp30)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1228(line=64, offs=5) -- 1235(line=64, offs=12)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret23, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret23, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret23, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1169(line=61, offs=27) -- 1244(line=65, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1250(line=65, offs=14) -- 1256(line=65, offs=20)
*/

ATSINSmove_nil(tmpret23) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1092(line=58, offs=34) -- 1263(line=66, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret23) ;
} /* end of [enemy_move_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1335(line=71, offs=26) -- 1669(line=81, offs=2)
*/
/*
local: 
global: player_keyPress$4$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_keyPress()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret32) ;
// ATStmpdec_void(tmp33) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp37) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp40) ;
ATStmpdec(tmp41, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp43, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1320(line=71, offs=11) -- 1669(line=81, offs=2)
*/
ATSINSflab(__patsflab_player_keyPress):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1342(line=72, offs=1) -- 1669(line=81, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1364(line=74, offs=8) -- 1382(line=74, offs=26)
*/
ATSINSmove(tmp35, check_key(ATSPMVintrep(37))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1364(line=74, offs=8) -- 1387(line=74, offs=31)
*/
ATSINSmove(tmp34, ats2jspre_eq_int0_int0(tmp35, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1361(line=74, offs=5) -- 1424(line=74, offs=68)
*/
ATSif(
tmp34
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1405(line=74, offs=49) -- 1418(line=74, offs=62)
*/
ATSINSmove(tmp36, ats2jspre_neg_double(ATSPMVfloat(20.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1393(line=74, offs=37) -- 1424(line=74, offs=68)
*/
ATSINSmove_void(tmp33, player_move(tmp36, ATSPMVf0loat(0.0))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1424(line=74, offs=68) -- 1424(line=74, offs=68)
*/
ATSINSmove_void(tmp33, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1445(line=76, offs=8) -- 1464(line=76, offs=27)
*/
ATSINSmove(tmp39, check_key(ATSPMVintrep(39))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1445(line=76, offs=8) -- 1469(line=76, offs=32)
*/
ATSINSmove(tmp38, ats2jspre_eq_int0_int0(tmp39, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1442(line=76, offs=5) -- 1505(line=76, offs=68)
*/
ATSif(
tmp38
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1475(line=76, offs=38) -- 1505(line=76, offs=68)
*/
ATSINSmove_void(tmp37, player_move(ATSPMVfloat(20.000000000000000000), ATSPMVf0loat(0.0))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1505(line=76, offs=68) -- 1505(line=76, offs=68)
*/
ATSINSmove_void(tmp37, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1526(line=78, offs=8) -- 1542(line=78, offs=24)
*/
ATSINSmove(tmp42, check_key(ATSPMVintrep(38))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1526(line=78, offs=8) -- 1547(line=78, offs=29)
*/
ATSINSmove(tmp41, ats2jspre_eq_int0_int0(tmp42, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1523(line=78, offs=5) -- 1584(line=78, offs=66)
*/
ATSif(
tmp41
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1553(line=78, offs=35) -- 1584(line=78, offs=66)
*/
ATSINSmove_void(tmp40, player_move(ATSPMVf0loat(0.0), ATSPMVfloat(20.000000000000000000))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1584(line=78, offs=66) -- 1584(line=78, offs=66)
*/
ATSINSmove_void(tmp40, ATSPMVempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1605(line=80, offs=8) -- 1623(line=80, offs=26)
*/
ATSINSmove(tmp44, check_key(ATSPMVintrep(40))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1605(line=80, offs=8) -- 1628(line=80, offs=31)
*/
ATSINSmove(tmp43, ats2jspre_eq_int0_int0(tmp44, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1602(line=80, offs=5) -- 1666(line=80, offs=69)
*/
ATSif(
tmp43
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1652(line=80, offs=55) -- 1665(line=80, offs=68)
*/
ATSINSmove(tmp45, ats2jspre_neg_double(ATSPMVfloat(20.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1634(line=80, offs=37) -- 1666(line=80, offs=69)
*/
ATSINSmove_void(tmpret32, player_move(ATSPMVf0loat(0.0), tmp45)) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1666(line=80, offs=69) -- 1666(line=80, offs=69)
*/
ATSINSmove_void(tmpret32, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1342(line=72, offs=1) -- 1669(line=81, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret32) ;
} /* end of [player_keyPress] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1717(line=83, offs=22) -- 2277(line=102, offs=2)
*/
/*
local: 
global: player_move$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_move(atstkind_t0ype(atstype_double) arg0, atstkind_t0ype(atstype_double) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret46) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp49, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp50, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp52, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp53, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp54, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp55, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp56, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp57, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp58, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp59, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp60, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp61, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp62, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp63, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1706(line=83, offs=11) -- 2277(line=102, offs=2)
*/
ATSINSflab(__patsflab_player_move):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1739(line=85, offs=8) -- 1746(line=85, offs=15)
*/
ATSINSmove(tmp47, ats2jspre_eq_double_double(arg0, ATSPMVf0loat(0.0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1736(line=85, offs=5) -- 2274(line=101, offs=8)
*/
ATSif(
tmp47
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1752(line=85, offs=21) -- 2008(line=93, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1785(line=86, offs=21) -- 1807(line=86, offs=43)
*/
ATSINSmove(tmp48, player_getPosition_Y()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1843(line=88, offs=16) -- 1904(line=88, offs=77)
*/
ATSINSmove(tmp51, ats2jspre_add_double_double(tmp48, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1843(line=88, offs=16) -- 1904(line=88, offs=77)
*/
ATSINSmove(tmp50, ats2jspre_gt_double_double(tmp51, ATSPMVfloat(500.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1843(line=88, offs=16) -- 1904(line=88, offs=77)
*/
ATSif(
tmp50
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1843(line=88, offs=16) -- 1904(line=88, offs=77)
*/
ATSINSmove(tmp49, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1843(line=88, offs=16) -- 1904(line=88, offs=77)
*/
ATSINSmove(tmp52, ats2jspre_add_double_double(tmp48, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1843(line=88, offs=16) -- 1904(line=88, offs=77)
*/
ATSINSmove(tmp53, ats2jspre_div_double_double(ATSPMVfloat(18.000000000000000000), ATSPMVf0loat(2.0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1843(line=88, offs=16) -- 1904(line=88, offs=77)
*/
ATSINSmove(tmp49, ats2jspre_lte_double_double(tmp52, tmp53)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1840(line=88, offs=13) -- 1979(line=90, offs=49)
*/
ATSif(
tmp49
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1927(line=89, offs=17) -- 1929(line=89, offs=19)
*/
ATSINSmove_void(tmpret46, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1969(line=90, offs=39) -- 1978(line=90, offs=48)
*/
ATSINSmove(tmp54, ats2jspre_add_double_double(tmp48, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1948(line=90, offs=18) -- 1979(line=90, offs=49)
*/
ATSINSmove_void(tmpret46, player_setPosition_Y(tmp54)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1752(line=85, offs=21) -- 2008(line=93, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2014(line=93, offs=14) -- 2274(line=101, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2039(line=94, offs=21) -- 2061(line=94, offs=43)
*/
ATSINSmove(tmp55, player_getPosition_X()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSINSmove(tmp58, ats2jspre_add_double_double(tmp55, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSINSmove(tmp60, ats2jspre_div_double_int(ATSPMVfloat(18.000000000000000000), ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSINSmove(tmp59, ats2jspre_sub_double_double(ATSPMVfloat(400.000000000000000000), tmp60)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSINSmove(tmp57, ats2jspre_gt_double_double(tmp58, tmp59)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSif(
tmp57
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSINSmove(tmp56, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSINSmove(tmp61, ats2jspre_add_double_double(tmp55, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSINSmove(tmp62, ats2jspre_div_double_int(ATSPMVfloat(18.000000000000000000), ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2097(line=96, offs=16) -- 2170(line=96, offs=89)
*/
ATSINSmove(tmp56, ats2jspre_lt_double_double(tmp61, tmp62)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2094(line=96, offs=13) -- 2245(line=98, offs=49)
*/
ATSif(
tmp56
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2193(line=97, offs=17) -- 2195(line=97, offs=19)
*/
ATSINSmove_void(tmpret46, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2235(line=98, offs=39) -- 2244(line=98, offs=48)
*/
ATSINSmove(tmp63, ats2jspre_add_double_double(tmp55, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2214(line=98, offs=18) -- 2245(line=98, offs=49)
*/
ATSINSmove_void(tmpret46, player_setPosition_X(tmp63)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2014(line=93, offs=14) -- 2274(line=101, offs=8)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret46) ;
} /* end of [player_move] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2315(line=104, offs=20) -- 2491(line=114, offs=2)
*/
/*
local: 
global: game_tick$6$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
game_tick(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret64) ;
// ATStmpdec_void(tmp65) ;
// ATStmpdec_void(tmp66) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2306(line=104, offs=11) -- 2491(line=114, offs=2)
*/
ATSINSflab(__patsflab_game_tick):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2328(line=106, offs=3) -- 2488(line=113, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2346(line=107, offs=14) -- 2361(line=107, offs=29)
*/
ATSINSmove_void(tmp65, enemy_update(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2377(line=108, offs=14) -- 2392(line=108, offs=29)
*/
ATSINSmove_void(tmp66, score_update(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2408(line=109, offs=14) -- 2424(line=109, offs=30)
*/
ATSINSmove_void(tmpret64, player_update(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2328(line=106, offs=3) -- 2488(line=113, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret64) ;
} /* end of [game_tick] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2535(line=116, offs=24) -- 2577(line=119, offs=2)
*/
/*
local: 
global: player_update$7$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_update(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret67) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2522(line=116, offs=11) -- 2577(line=119, offs=2)
*/
ATSINSflab(__patsflab_player_update):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2543(line=117, offs=1) -- 2577(line=119, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2557(line=118, offs=12) -- 2574(line=118, offs=29)
*/
ATSINSmove_void(tmpret67, player_keyPress()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2543(line=117, offs=1) -- 2577(line=119, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret67) ;
} /* end of [player_update] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2624(line=121, offs=23) -- 2819(line=133, offs=4)
*/
/*
local: 
global: enemy_update$8$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
enemy_update(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret68) ;
ATStmpdec(tmp69, atstype_boxed) ;
ATStmpdec(tmp70, gameobject) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2612(line=121, offs=11) -- 2819(line=133, offs=4)
*/
ATSINSflab(__patsflab_enemy_update):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2632(line=122, offs=1) -- 2819(line=133, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2649(line=123, offs=13) -- 2661(line=123, offs=25)
*/
ATSINSmove(tmp69, enemy_get(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2670(line=125, offs=3) -- 2814(line=132, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2688(line=126, offs=5) -- 2694(line=126, offs=11)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2649(line=123, offs=13) -- 2661(line=123, offs=25)
*/
ATSifthen(ATSCKptriscons(tmp69)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2694(line=126, offs=11) -- 2694(line=126, offs=11)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2698(line=126, offs=15) -- 2700(line=126, offs=17)
*/
ATSINSmove_void(tmpret68, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2706(line=127, offs=5) -- 2712(line=127, offs=11)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2649(line=123, offs=13) -- 2661(line=123, offs=25)
*/
ATSifthen(ATSCKptrisnull(tmp69)) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2670(line=125, offs=3) -- 2814(line=132, offs=6)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2712(line=127, offs=11) -- 2712(line=127, offs=11)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2717(line=127, offs=16) -- 2814(line=132, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2738(line=128, offs=17) -- 2752(line=128, offs=31)
*/
ATSINSmove(tmp70, create_enemy()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2767(line=129, offs=14) -- 2792(line=129, offs=39)
*/
ATSINSmove_void(tmpret68, set_enemy_animation(tmp70)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2717(line=127, offs=16) -- 2814(line=132, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2632(line=122, offs=1) -- 2819(line=133, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret68) ;
} /* end of [enemy_update] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2852(line=135, offs=30) -- 3289(line=148, offs=4)
*/
/*
local: 
global: set_enemy_animation$9$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
set_enemy_animation(gameobject arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret71) ;
ATStmpdec(tmp72, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp73, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp74, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp75, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp76, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp77, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp78, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp79, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp80, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2833(line=135, offs=11) -- 3289(line=148, offs=4)
*/
ATSINSflab(__patsflab_set_enemy_animation):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2864(line=136, offs=1) -- 3289(line=148, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2887(line=137, offs=18) -- 2909(line=137, offs=40)
*/
ATSINSmove(tmp72, player_getPosition_X()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2928(line=138, offs=18) -- 2950(line=138, offs=40)
*/
ATSINSmove(tmp73, player_getPosition_Y()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2968(line=139, offs=17) -- 2993(line=139, offs=42)
*/
ATSINSmove(tmp74, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3012(line=140, offs=17) -- 3037(line=140, offs=42)
*/
ATSINSmove(tmp75, enemy_getPosition_Y(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3055(line=141, offs=16) -- 3073(line=141, offs=34)
*/
ATSINSmove(tmp76, ats2jspre_sub_double_double(tmp72, tmp74)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3090(line=142, offs=16) -- 3108(line=142, offs=34)
*/
ATSINSmove(tmp77, ats2jspre_sub_double_double(tmp73, tmp75)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3124(line=143, offs=15) -- 3139(line=143, offs=30)
*/
ATSINSmove(tmp78, ats2jspre_div_double_double(tmp76, tmp77)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3157(line=144, offs=17) -- 3175(line=144, offs=35)
*/
ATSINSmove(tmp79, calc_speed_x(tmp78)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3194(line=145, offs=17) -- 3209(line=145, offs=32)
*/
ATSINSmove(tmp80, ats2jspre_mul_double_double(tmp78, tmp79)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3219(line=147, offs=5) -- 3284(line=147, offs=70)
*/
ATSINSmove_void(tmpret71, enemy_move(arg0, tmp79, tmp80, ATSPMVcfunlab(-1, __patsfun_10, (arg0)))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2864(line=136, offs=1) -- 3289(line=148, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret71) ;
} /* end of [set_enemy_animation] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3255(line=147, offs=41) -- 3283(line=147, offs=69)
*/
/*
local: 
global: __patsfun_10$0(level=1)
local: enemy$183(1)(HSEcst(gameobject))
global: enemy$183(1)(HSEcst(gameobject))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_10(gameobject env0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret81) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3255(line=147, offs=41) -- 3283(line=147, offs=69)
*/
ATSINSflab(__patsflab___patsfun_10):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3264(line=147, offs=50) -- 3282(line=147, offs=68)
*/
ATSINSmove_void(tmpret81, player_crash(env0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret81) ;
} /* end of [__patsfun_10] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3315(line=150, offs=23) -- 3489(line=157, offs=4)
*/
/*
local: 
global: player_crash$11$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_crash(gameobject arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret82) ;
// ATStmpdec_void(tmp83) ;
ATStmpdec(tmp84, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3303(line=150, offs=11) -- 3489(line=157, offs=4)
*/
ATSINSflab(__patsflab_player_crash):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3325(line=150, offs=33) -- 3489(line=157, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3340(line=151, offs=11) -- 3358(line=151, offs=29)
*/
ATSINSmove_void(tmp83, enemy_remove(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3373(line=152, offs=13) -- 3385(line=152, offs=25)
*/
ATSINSmove(tmp84, player_get()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3393(line=154, offs=3) -- 3484(line=156, offs=18)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3410(line=155, offs=5) -- 3416(line=155, offs=11)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3373(line=152, offs=13) -- 3385(line=152, offs=25)
*/
ATSifthen(ATSCKptriscons(tmp84)) { ATSINSgoto(__atstmplab7) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3416(line=155, offs=11) -- 3416(line=155, offs=11)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3420(line=155, offs=15) -- 3422(line=155, offs=17)
*/
ATSINSmove_void(tmpret82, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3471(line=156, offs=5) -- 3477(line=156, offs=11)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3373(line=152, offs=13) -- 3385(line=152, offs=25)
*/
ATSifthen(ATSCKptrisnull(tmp84)) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3393(line=154, offs=3) -- 3484(line=156, offs=18)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3477(line=156, offs=11) -- 3477(line=156, offs=11)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3482(line=156, offs=16) -- 3484(line=156, offs=18)
*/
ATSINSmove_void(tmpret82, ATSPMVempty()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3325(line=150, offs=33) -- 3489(line=157, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret82) ;
} /* end of [player_crash] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3513(line=159, offs=21) -- 4128(line=177, offs=4)
*/
/*
local: 
global: enemy_move$12$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
enemy_move(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2, atstype_cloptr arg3)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret85) ;
ATStmpdec(tmp86, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp87, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp88, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp89, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp90) ;
ATStmpdec(tmp91, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp92, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3503(line=159, offs=11) -- 4128(line=177, offs=4)
*/
ATSINSflab(__patsflab_enemy_move):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3546(line=160, offs=1) -- 4128(line=177, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3567(line=161, offs=17) -- 3592(line=161, offs=42)
*/
ATSINSmove(tmp86, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3611(line=162, offs=17) -- 3636(line=162, offs=42)
*/
ATSINSmove(tmp87, enemy_getPosition_Y(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3655(line=163, offs=17) -- 3672(line=163, offs=34)
*/
ATSINSmove(tmp88, ats2jspre_add_double_double(tmp86, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3690(line=164, offs=17) -- 3707(line=164, offs=34)
*/
ATSINSmove(tmp89, ats2jspre_add_double_double(tmp87, arg2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3720(line=165, offs=12) -- 3762(line=165, offs=54)
*/
ATSINSmove_void(tmp90, enemy_setPosition(arg0, tmp88, tmp89)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3778(line=166, offs=15) -- 3820(line=166, offs=57)
*/
ATSINSmove(tmp91, enemy_check_crash(arg0, tmp88, tmp89)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3828(line=168, offs=3) -- 4123(line=176, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3848(line=169, offs=5) -- 3849(line=169, offs=6)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3778(line=166, offs=15) -- 3820(line=166, offs=57)
*/
ATSifnthen(ATSCKpat_int(tmp91, ATSPMVint(1))) { ATSINSgoto(__atstmplab10) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3849(line=169, offs=6) -- 3849(line=169, offs=6)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3853(line=169, offs=10) -- 3856(line=169, offs=13)
*/
ATSINSmove_void(tmpret85, ATSfunclo_clo(arg3, (atstype_cloptr), atsvoid_t0ype)(arg3)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3869(line=170, offs=5) -- 3870(line=170, offs=6)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3778(line=166, offs=15) -- 3820(line=166, offs=57)
*/
ATSifnthen(ATSCKpat_int(tmp91, ATSPMVint(0))) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3828(line=168, offs=3) -- 4123(line=176, offs=6)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3870(line=170, offs=6) -- 3870(line=170, offs=6)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3874(line=170, offs=10) -- 4123(line=176, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3913(line=171, offs=23) -- 3955(line=171, offs=65)
*/
ATSINSmove(tmp92, enemy_check_bound(arg0, tmp88, tmp89)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3967(line=173, offs=5) -- 4111(line=175, offs=86)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3995(line=174, offs=7) -- 3996(line=174, offs=8)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3913(line=171, offs=23) -- 3955(line=171, offs=65)
*/
ATSifnthen(ATSCKpat_int(tmp92, ATSPMVint(1))) { ATSINSgoto(__atstmplab14) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3996(line=174, offs=8) -- 3996(line=174, offs=8)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4000(line=174, offs=12) -- 4018(line=174, offs=30)
*/
ATSINSmove_void(tmpret85, panel_remove(arg0)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4032(line=175, offs=7) -- 4033(line=175, offs=8)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3913(line=171, offs=23) -- 3955(line=171, offs=65)
*/
ATSifnthen(ATSCKpat_int(tmp92, ATSPMVint(0))) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3967(line=173, offs=5) -- 4111(line=175, offs=86)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4033(line=175, offs=8) -- 4033(line=175, offs=8)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4037(line=175, offs=12) -- 4111(line=175, offs=86)
*/
ATSINSmove_void(tmpret85, setTimeout_cloref(ATSPMVcfunlab(-1, __patsfun_13, (arg0, arg1, arg2, arg3)), ATSPMVf0loat(20.0))) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3874(line=170, offs=10) -- 4123(line=176, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3546(line=160, offs=1) -- 4128(line=177, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret85) ;
} /* end of [enemy_move] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4055(line=175, offs=30) -- 4104(line=175, offs=79)
*/
/*
local: 
global: __patsfun_13$0(level=1)
local: enemy$195(1)(HSEcst(gameobject)), speed_x$196(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), speed_y$197(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), k$198(1)(HSEfun(; HSEcst(atsvoid_t0ype)))
global: enemy$195(1)(HSEcst(gameobject)), speed_x$196(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), speed_y$197(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), k$198(1)(HSEfun(; HSEcst(atsvoid_t0ype)))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_13(gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret93) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4055(line=175, offs=30) -- 4104(line=175, offs=79)
*/
ATSINSflab(__patsflab___patsfun_13):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4065(line=175, offs=40) -- 4103(line=175, offs=78)
*/
ATSINSmove_void(tmpret93, enemy_move(env0, env1, env2, env3)) ;

ATSfunbody_end()
ATSreturn_void(tmpret93) ;
} /* end of [__patsfun_13] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4159(line=179, offs=28) -- 4756(line=193, offs=4)
*/
/*
local: 
global: enemy_check_crash$14$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_crash(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret94, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp95, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp96, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp97, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp98, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp99, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp100, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp101, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp102, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp103) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4142(line=179, offs=11) -- 4756(line=193, offs=4)
*/
ATSINSflab(__patsflab_enemy_check_crash):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4187(line=179, offs=56) -- 4756(line=193, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4209(line=180, offs=18) -- 4231(line=180, offs=40)
*/
ATSINSmove(tmp95, player_getPosition_X()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4250(line=181, offs=18) -- 4272(line=181, offs=40)
*/
ATSINSmove(tmp96, player_getPosition_Y()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4290(line=182, offs=17) -- 4315(line=182, offs=42)
*/
ATSINSmove(tmp97, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4334(line=183, offs=17) -- 4359(line=183, offs=42)
*/
ATSINSmove(tmp98, enemy_getPosition_Y(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4375(line=184, offs=14) -- 4422(line=184, offs=61)
*/
ATSINSmove(tmp99, calc_dist(tmp95, tmp96, tmp97, tmp98)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4536(line=185, offs=20) -- 4562(line=185, offs=46)
*/
ATSINSmove(tmp101, ats2jspre_add_double_double(ATSPMVfloat(18.000000000000000000), ATSPMVfloat(18.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4535(line=185, offs=19) -- 4569(line=185, offs=53)
*/
ATSINSmove(tmp100, ats2jspre_div_double_double(tmp101, ATSPMVf0loat(2.0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4637(line=188, offs=6) -- 4653(line=188, offs=22)
*/
ATSINSmove(tmp102, ats2jspre_lt_double_double(tmp99, tmp100)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4634(line=188, offs=3) -- 4751(line=192, offs=13)
*/
ATSif(
tmp102
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4659(line=188, offs=28) -- 4744(line=192, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4676(line=189, offs=13) -- 4726(line=189, offs=63)
*/
ATSINSmove_void(tmp103, crash_report(tmp95, tmp96, tmp97, tmp98)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4736(line=191, offs=3) -- 4737(line=191, offs=4)
*/
ATSINSmove(tmpret94, ATSPMVi0nt(1)) ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4659(line=188, offs=28) -- 4744(line=192, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4750(line=192, offs=12) -- 4751(line=192, offs=13)
*/
ATSINSmove(tmpret94, ATSPMVi0nt(0)) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4187(line=179, offs=56) -- 4756(line=193, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret94) ;
} /* end of [enemy_check_crash] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4787(line=195, offs=28) -- 4922(line=197, offs=9)
*/
/*
local: 
global: enemy_check_bound$15$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_bound(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret104, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp105, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp106, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp107, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp108, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4770(line=195, offs=11) -- 4922(line=197, offs=9)
*/
ATSINSflab(__patsflab_enemy_check_bound):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSINSmove(tmp108, ats2jspre_gt_double_double(arg1, ATSPMVfloat(400.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSif(
tmp108
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSINSmove(tmp107, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSINSmove(tmp107, ats2jspre_lt_double_double(arg1, ATSPMVf0loat(0.0))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSif(
tmp107
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSINSmove(tmp106, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSINSmove(tmp106, ats2jspre_gt_double_double(arg2, ATSPMVfloat(500.000000000000000000))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSif(
tmp106
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSINSmove(tmp105, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4822(line=196, offs=6) -- 4905(line=196, offs=89)
*/
ATSINSmove(tmp105, ats2jspre_lt_double_double(arg2, ATSPMVf0loat(0.0))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4819(line=196, offs=3) -- 4922(line=197, offs=9)
*/
ATSif(
tmp105
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4911(line=196, offs=95) -- 4912(line=196, offs=96)
*/
ATSINSmove(tmpret104, ATSPMVi0nt(1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4921(line=197, offs=8) -- 4922(line=197, offs=9)
*/
ATSINSmove(tmpret104, ATSPMVi0nt(0)) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret104) ;
} /* end of [enemy_check_bound] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 5011(line=200, offs=21) -- 5028(line=200, offs=38)
*/
/*
local: 
global: cloref_app$16$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
cloref_app(atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret109) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 5001(line=200, offs=11) -- 5028(line=200, offs=38)
*/
ATSINSflab(__patsflab_cloref_app):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 5021(line=200, offs=31) -- 5028(line=200, offs=38)
*/
ATSINSmove_void(tmpret109, ATSfunclo_clo(arg0, (atstype_cloptr), atsvoid_t0ype)(arg0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret109) ;
} /* end of [cloref_app] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 359(line=23, offs=16) -- 370(line=23, offs=27)
*/
ATSINSmove(statmp0, ats2jspre_ref(ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 391(line=24, offs=20) -- 410(line=24, offs=39)
*/
ATSINSmove(statmp1, ats2jspre_ref(ATSPMVintrep(100))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 428(line=25, offs=16) -- 440(line=25, offs=28)
*/
ATSINSmove(statmp2, ats2jspre_ref(ATSPMVi0nt(10))) ;

/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
ATSextern()
atsvoid_t0ype
my_dynload()
{
ATSfunbody_beg()
ATSINSmove_void(tmpret_void, _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynload()) ;
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} // end-of-dynload-alias
/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 5032(line=202, offs=1) -- 5455(line=225, offs=3)
*/
ATSextcode_beg()
function
ATS_start()
{
  var _ = my_dynload();
  var _ = init();
}

function
test(x, y, z, a){
  console.log("player:" + x + ", " + y + "; enemy:" + z + ", " + a);
}

function
crash_report(x, y, z, a){
  console.log("crash found => player:" + x + ", " + y + "; enemy:" + z + ", " + a);
}

function
setTimeout_cloref(fwork, ntime)
{
  setTimeout(function(){cloref_app(fwork);return;}, ntime);
}
ATSextcode_end()

/* ****** ****** */

/* end-of-compilation-unit */
