/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-4-28:  1h:58m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/list.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 357(line=27, offs=1) -- 396(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 423(line=32, offs=1) -- 455(line=32, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 482(line=36, offs=1) -- 512(line=36, offs=31)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/print.sats: 189(line=14, offs=1) -- 218(line=14, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 513(line=37, offs=1) -- 545(line=37, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/filebas.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 572(line=41, offs=1) -- 601(line=41, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/list.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/option.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 359(line=27, offs=1) -- 398(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 425(line=32, offs=1) -- 457(line=32, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 484(line=36, offs=1) -- 515(line=36, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/option.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 359(line=27, offs=1) -- 398(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 425(line=32, offs=1) -- 457(line=33, offs=25)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 461(line=35, offs=1) -- 491(line=35, offs=31)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/print.sats: 189(line=14, offs=1) -- 218(line=14, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 516(line=39, offs=1) -- 547(line=39, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/reference.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSmath.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSdate.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSarray.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSglobal.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(ats2jspre_ref)
ATSdyncst_mac(store_init)
ATSdyncst_mac(player_init)
ATSdyncst_mac(ats2jspre_gt_int0_int0)
ATSdyncst_mac(ats2jspre_ref_get_elt)
ATSdyncst_mac(ats2jspre_ref_set_elt)
ATSdyncst_mac(ats2jspre_sub_int0_int0)
ATSdyncst_mac(update_lives)
ATSdyncst_mac(gameover)
ATSdyncst_mac(ats2jspre_lte_int0_int0)
ATSdyncst_mac(ats2jspre_add_int0_int0)
ATSdyncst_mac(ats2jspre_eq_int0_int0)
ATSdyncst_mac(check_key)
ATSdyncst_mac(player_move)
ATSdyncst_mac(ats2jspre_neg_double)
ATSdyncst_mac(ats2jspre_eq_double_double)
ATSdyncst_mac(player_getPosition_Y)
ATSdyncst_mac(ats2jspre_gt_double_double)
ATSdyncst_mac(ats2jspre_add_double_double)
ATSdyncst_mac(ats2jspre_lte_double_double)
ATSdyncst_mac(ats2jspre_div_double_double)
ATSdyncst_mac(player_setPosition_Y)
ATSdyncst_mac(player_getPosition_X)
ATSdyncst_mac(ats2jspre_sub_double_double)
ATSdyncst_mac(ats2jspre_div_double_int)
ATSdyncst_mac(ats2jspre_lt_double_double)
ATSdyncst_mac(player_setPosition_X)
ATSdyncst_mac(enemy_update)
ATSdyncst_mac(player_update)
ATSdyncst_mac(player_keyPress)
ATSdyncst_mac(enemy_get)
ATSdyncst_mac(create_enemy)
ATSdyncst_mac(set_enemy_animation)
ATSdyncst_mac(enemy_getPosition_X)
ATSdyncst_mac(enemy_getPosition_Y)
ATSdyncst_mac(ats2jspre_mul_double_double)
ATSdyncst_mac(test)
ATSdyncst_mac(enemy_move)
ATSdyncst_mac(enemy_remove)
ATSdyncst_mac(enemy_setPosition)
ATSdyncst_mac(enemy_check_crash)
ATSdyncst_mac(enemy_check_bound)
ATSdyncst_mac(setTimeout_cloref)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatmpdec(statmp0, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp1, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp2, store) ;
ATSstatmpdec(statmp3, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp4, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp5, atstkind_type(atstype_ptrk)) ;
// ATSstatmpdec_void(statmp34) ;
ATSstatic()
atsvoid_t0ype
init_0() ;

#if(0)
ATSextern()
atstype_boxed
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
enemy_get(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
enemy_move_get(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_keyPress() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_move(atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
game_tick(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_update(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
enemy_update(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
set_enemy_animation(gameobject) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
__patsfun_10(gameobject) ;

ATSstatic()
atsvoid_t0ype
__patsfun_11(gameobject) ;

#if(0)
ATSextern()
atsvoid_t0ype
enemy_move(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
__patsfun_13(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_funptr) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_crash(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_bound(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

ATSclosurerize_beg(__patsfun_10, (gameobject), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
gameobject env0 ;
} __patsfun_10__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_10__cfun
(
__patsfun_10__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_10(p_cenv->env0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_10__closureinit
(
__patsfun_10__closure_t0ype *p_cenv, gameobject env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_10__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_10__closurerize
(
gameobject env0
)
{
return __patsfun_10__closureinit(ATS_MALLOC(sizeof(__patsfun_10__closure_t0ype)), env0) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(__patsfun_11, (gameobject), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
gameobject env0 ;
} __patsfun_11__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_11__cfun
(
__patsfun_11__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_11(p_cenv->env0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_11__closureinit
(
__patsfun_11__closure_t0ype *p_cenv, gameobject env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_11__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_11__closurerize
(
gameobject env0
)
{
return __patsfun_11__closureinit(ATS_MALLOC(sizeof(__patsfun_11__closure_t0ype)), env0) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(__patsfun_13, (gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_funptr), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
gameobject env0 ;
atstkind_t0ype(atstype_double) env1 ;
atstkind_t0ype(atstype_double) env2 ;
atstype_funptr env3 ;
} __patsfun_13__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_13__cfun
(
__patsfun_13__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_13(p_cenv->env0, p_cenv->env1, p_cenv->env2, p_cenv->env3)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_13__closureinit
(
__patsfun_13__closure_t0ype *p_cenv, gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->env2 = env2 ;
p_cenv->env3 = env3 ;
p_cenv->cfun = __patsfun_13__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_13__closurerize
(
gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3
)
{
return __patsfun_13__closureinit(ATS_MALLOC(sizeof(__patsfun_13__closure_t0ype)), env0, env1, env2, env3) ;
} /* end of [closurerize] */
ATSclosurerize_end()
/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 538(line=30, offs=7) -- 691(line=36, offs=4)
*/
/*
local: 
global: init_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
init_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 538(line=30, offs=7) -- 691(line=36, offs=4)
*/
ATSINSflab(__patsflab_init_0):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 556(line=31, offs=3) -- 691(line=36, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 592(line=33, offs=14) -- 605(line=33, offs=27)
*/
ATSINSmove_void(tmpret6, player_init()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 556(line=31, offs=3) -- 691(line=36, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret6) ;
} /* end of [init_0] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 717(line=38, offs=23) -- 941(line=48, offs=8)
*/
/*
local: 
global: player_get$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstype_boxed) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp10) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp13) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp15) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 707(line=38, offs=13) -- 941(line=48, offs=8)
*/
ATSINSflab(__patsflab_player_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 731(line=39, offs=8) -- 739(line=39, offs=16)
*/
ATSINSmove(tmp9, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 731(line=39, offs=8) -- 743(line=39, offs=20)
*/
ATSINSmove(tmp8, ats2jspre_gt_int0_int0(tmp9, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 728(line=39, offs=5) -- 941(line=48, offs=8)
*/
ATSif(
tmp8
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 749(line=39, offs=26) -- 870(line=44, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 782(line=40, offs=29) -- 790(line=40, offs=37)
*/
ATSINSmove(tmp12, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 782(line=40, offs=29) -- 794(line=40, offs=41)
*/
ATSINSmove(tmp11, ats2jspre_sub_int0_int0(tmp12, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 770(line=40, offs=17) -- 794(line=40, offs=41)
*/
ATSINSmove_void(tmp10, ats2jspre_ref_set_elt(statmp0, tmp11)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 826(line=41, offs=31) -- 834(line=41, offs=39)
*/
ATSINSmove(tmp14, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 813(line=41, offs=18) -- 835(line=41, offs=40)
*/
ATSINSmove_void(tmp13, update_lives(tmp14)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 854(line=43, offs=9) -- 861(line=43, offs=16)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret7, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret7, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret7, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 749(line=39, offs=26) -- 870(line=44, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 876(line=44, offs=14) -- 941(line=48, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 898(line=45, offs=18) -- 908(line=45, offs=28)
*/
ATSINSmove_void(tmp15, gameover()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 926(line=47, offs=9) -- 932(line=47, offs=15)
*/

ATSINSmove_nil(tmpret7) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 876(line=44, offs=14) -- 941(line=48, offs=8)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 966(line=50, offs=22) -- 1176(line=59, offs=6)
*/
/*
local: 
global: enemy_get$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
enemy_get(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret16, atstype_boxed) ;
// ATStmpdec_void(tmp17) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp22) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 957(line=50, offs=13) -- 1176(line=59, offs=6)
*/
ATSINSflab(__patsflab_enemy_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 973(line=50, offs=29) -- 1176(line=59, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1007(line=51, offs=30) -- 1019(line=51, offs=42)
*/
ATSINSmove(tmp19, ats2jspre_ref_get_elt(statmp4)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1007(line=51, offs=30) -- 1024(line=51, offs=47)
*/
ATSINSmove(tmp18, ats2jspre_sub_int0_int0(tmp19, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 991(line=51, offs=14) -- 1024(line=51, offs=47)
*/
ATSINSmove_void(tmp17, ats2jspre_ref_set_elt(statmp4, tmp18)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1039(line=53, offs=8) -- 1051(line=53, offs=20)
*/
ATSINSmove(tmp21, ats2jspre_ref_get_elt(statmp4)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1039(line=53, offs=8) -- 1056(line=53, offs=25)
*/
ATSINSmove(tmp20, ats2jspre_lte_int0_int0(tmp21, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1036(line=53, offs=5) -- 1169(line=58, offs=20)
*/
ATSif(
tmp20
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1062(line=53, offs=31) -- 1157(line=58, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1100(line=55, offs=32) -- 1112(line=55, offs=44)
*/
ATSINSmove(tmp24, ats2jspre_ref_get_elt(statmp4)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1100(line=55, offs=32) -- 1125(line=55, offs=57)
*/
ATSINSmove(tmp23, ats2jspre_add_int0_int0(tmp24, ATSPMVintrep(2000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1084(line=55, offs=16) -- 1125(line=55, offs=57)
*/
ATSINSmove_void(tmp22, ats2jspre_ref_set_elt(statmp4, tmp23)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1141(line=57, offs=7) -- 1148(line=57, offs=14)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret16, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret16, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret16, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1062(line=53, offs=31) -- 1157(line=58, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1163(line=58, offs=14) -- 1169(line=58, offs=20)
*/

ATSINSmove_nil(tmpret16) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 973(line=50, offs=29) -- 1176(line=59, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret16) ;
} /* end of [enemy_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1206(line=61, offs=27) -- 1384(line=69, offs=6)
*/
/*
local: 
global: enemy_move_get$3$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
enemy_move_get(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret25, atstype_boxed) ;
// ATStmpdec_void(tmp26) ;
ATStmpdec(tmp27, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp31) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1192(line=61, offs=13) -- 1384(line=69, offs=6)
*/
ATSINSflab(__patsflab_enemy_move_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1213(line=61, offs=34) -- 1384(line=69, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1243(line=62, offs=26) -- 1251(line=62, offs=34)
*/
ATSINSmove(tmp28, ats2jspre_ref_get_elt(statmp5)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1243(line=62, offs=26) -- 1256(line=62, offs=39)
*/
ATSINSmove(tmp27, ats2jspre_sub_int0_int0(tmp28, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1231(line=62, offs=14) -- 1256(line=62, offs=39)
*/
ATSINSmove_void(tmp26, ats2jspre_ref_set_elt(statmp5, tmp27)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1271(line=64, offs=8) -- 1279(line=64, offs=16)
*/
ATSINSmove(tmp30, ats2jspre_ref_get_elt(statmp5)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1271(line=64, offs=8) -- 1284(line=64, offs=21)
*/
ATSINSmove(tmp29, ats2jspre_lte_int0_int0(tmp30, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1268(line=64, offs=5) -- 1377(line=68, offs=20)
*/
ATSif(
tmp29
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1290(line=64, offs=27) -- 1365(line=68, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1322(line=65, offs=28) -- 1330(line=65, offs=36)
*/
ATSINSmove(tmp33, ats2jspre_ref_get_elt(statmp5)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1322(line=65, offs=28) -- 1335(line=65, offs=41)
*/
ATSINSmove(tmp32, ats2jspre_add_int0_int0(tmp33, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1310(line=65, offs=16) -- 1335(line=65, offs=41)
*/
ATSINSmove_void(tmp31, ats2jspre_ref_set_elt(statmp5, tmp32)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1349(line=67, offs=5) -- 1356(line=67, offs=12)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret25, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret25, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret25, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1290(line=64, offs=27) -- 1365(line=68, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1371(line=68, offs=14) -- 1377(line=68, offs=20)
*/

ATSINSmove_nil(tmpret25) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1213(line=61, offs=34) -- 1384(line=69, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret25) ;
} /* end of [enemy_move_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1454(line=74, offs=26) -- 1788(line=84, offs=2)
*/
/*
local: 
global: player_keyPress$4$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_keyPress()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret35) ;
// ATStmpdec_void(tmp36) ;
ATStmpdec(tmp37, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp40) ;
ATStmpdec(tmp41, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp43) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp46, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1439(line=74, offs=11) -- 1788(line=84, offs=2)
*/
ATSINSflab(__patsflab_player_keyPress):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1461(line=75, offs=1) -- 1788(line=84, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1483(line=77, offs=8) -- 1501(line=77, offs=26)
*/
ATSINSmove(tmp38, check_key(ATSPMVintrep(37))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1483(line=77, offs=8) -- 1506(line=77, offs=31)
*/
ATSINSmove(tmp37, ats2jspre_eq_int0_int0(tmp38, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1480(line=77, offs=5) -- 1543(line=77, offs=68)
*/
ATSif(
tmp37
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1524(line=77, offs=49) -- 1537(line=77, offs=62)
*/
ATSINSmove(tmp39, ats2jspre_neg_double(ATSPMVfloat(20.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1512(line=77, offs=37) -- 1543(line=77, offs=68)
*/
ATSINSmove_void(tmp36, player_move(tmp39, ATSPMVf0loat(0.0))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1543(line=77, offs=68) -- 1543(line=77, offs=68)
*/
ATSINSmove_void(tmp36, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1564(line=79, offs=8) -- 1583(line=79, offs=27)
*/
ATSINSmove(tmp42, check_key(ATSPMVintrep(39))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1564(line=79, offs=8) -- 1588(line=79, offs=32)
*/
ATSINSmove(tmp41, ats2jspre_eq_int0_int0(tmp42, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1561(line=79, offs=5) -- 1624(line=79, offs=68)
*/
ATSif(
tmp41
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1594(line=79, offs=38) -- 1624(line=79, offs=68)
*/
ATSINSmove_void(tmp40, player_move(ATSPMVfloat(20.000000000000000000), ATSPMVf0loat(0.0))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1624(line=79, offs=68) -- 1624(line=79, offs=68)
*/
ATSINSmove_void(tmp40, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1645(line=81, offs=8) -- 1661(line=81, offs=24)
*/
ATSINSmove(tmp45, check_key(ATSPMVintrep(38))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1645(line=81, offs=8) -- 1666(line=81, offs=29)
*/
ATSINSmove(tmp44, ats2jspre_eq_int0_int0(tmp45, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1642(line=81, offs=5) -- 1703(line=81, offs=66)
*/
ATSif(
tmp44
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1672(line=81, offs=35) -- 1703(line=81, offs=66)
*/
ATSINSmove_void(tmp43, player_move(ATSPMVf0loat(0.0), ATSPMVfloat(20.000000000000000000))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1703(line=81, offs=66) -- 1703(line=81, offs=66)
*/
ATSINSmove_void(tmp43, ATSPMVempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1724(line=83, offs=8) -- 1742(line=83, offs=26)
*/
ATSINSmove(tmp47, check_key(ATSPMVintrep(40))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1724(line=83, offs=8) -- 1747(line=83, offs=31)
*/
ATSINSmove(tmp46, ats2jspre_eq_int0_int0(tmp47, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1721(line=83, offs=5) -- 1785(line=83, offs=69)
*/
ATSif(
tmp46
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1771(line=83, offs=55) -- 1784(line=83, offs=68)
*/
ATSINSmove(tmp48, ats2jspre_neg_double(ATSPMVfloat(20.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1753(line=83, offs=37) -- 1785(line=83, offs=69)
*/
ATSINSmove_void(tmpret35, player_move(ATSPMVf0loat(0.0), tmp48)) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1785(line=83, offs=69) -- 1785(line=83, offs=69)
*/
ATSINSmove_void(tmpret35, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1461(line=75, offs=1) -- 1788(line=84, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret35) ;
} /* end of [player_keyPress] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1836(line=86, offs=22) -- 2396(line=105, offs=2)
*/
/*
local: 
global: player_move$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_move(atstkind_t0ype(atstype_double) arg0, atstkind_t0ype(atstype_double) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret49) ;
ATStmpdec(tmp50, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp52, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp53, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp54, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp55, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp56, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp57, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp58, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp59, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp60, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp61, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp62, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp63, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp64, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp65, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp66, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1825(line=86, offs=11) -- 2396(line=105, offs=2)
*/
ATSINSflab(__patsflab_player_move):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1858(line=88, offs=8) -- 1865(line=88, offs=15)
*/
ATSINSmove(tmp50, ats2jspre_eq_double_double(arg0, ATSPMVf0loat(0.0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1855(line=88, offs=5) -- 2393(line=104, offs=8)
*/
ATSif(
tmp50
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1871(line=88, offs=21) -- 2127(line=96, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1904(line=89, offs=21) -- 1926(line=89, offs=43)
*/
ATSINSmove(tmp51, player_getPosition_Y()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1962(line=91, offs=16) -- 2023(line=91, offs=77)
*/
ATSINSmove(tmp54, ats2jspre_add_double_double(tmp51, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1962(line=91, offs=16) -- 2023(line=91, offs=77)
*/
ATSINSmove(tmp53, ats2jspre_gt_double_double(tmp54, ATSPMVfloat(500.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1962(line=91, offs=16) -- 2023(line=91, offs=77)
*/
ATSif(
tmp53
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1962(line=91, offs=16) -- 2023(line=91, offs=77)
*/
ATSINSmove(tmp52, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1962(line=91, offs=16) -- 2023(line=91, offs=77)
*/
ATSINSmove(tmp55, ats2jspre_add_double_double(tmp51, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1962(line=91, offs=16) -- 2023(line=91, offs=77)
*/
ATSINSmove(tmp56, ats2jspre_div_double_double(ATSPMVfloat(18.000000000000000000), ATSPMVf0loat(2.0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1962(line=91, offs=16) -- 2023(line=91, offs=77)
*/
ATSINSmove(tmp52, ats2jspre_lte_double_double(tmp55, tmp56)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1959(line=91, offs=13) -- 2098(line=93, offs=49)
*/
ATSif(
tmp52
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2046(line=92, offs=17) -- 2048(line=92, offs=19)
*/
ATSINSmove_void(tmpret49, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2088(line=93, offs=39) -- 2097(line=93, offs=48)
*/
ATSINSmove(tmp57, ats2jspre_add_double_double(tmp51, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2067(line=93, offs=18) -- 2098(line=93, offs=49)
*/
ATSINSmove_void(tmpret49, player_setPosition_Y(tmp57)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1871(line=88, offs=21) -- 2127(line=96, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2133(line=96, offs=14) -- 2393(line=104, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2158(line=97, offs=21) -- 2180(line=97, offs=43)
*/
ATSINSmove(tmp58, player_getPosition_X()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSINSmove(tmp61, ats2jspre_add_double_double(tmp58, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSINSmove(tmp63, ats2jspre_div_double_int(ATSPMVfloat(18.000000000000000000), ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSINSmove(tmp62, ats2jspre_sub_double_double(ATSPMVfloat(400.000000000000000000), tmp63)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSINSmove(tmp60, ats2jspre_gt_double_double(tmp61, tmp62)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSif(
tmp60
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSINSmove(tmp59, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSINSmove(tmp64, ats2jspre_add_double_double(tmp58, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSINSmove(tmp65, ats2jspre_div_double_int(ATSPMVfloat(18.000000000000000000), ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2216(line=99, offs=16) -- 2289(line=99, offs=89)
*/
ATSINSmove(tmp59, ats2jspre_lt_double_double(tmp64, tmp65)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2213(line=99, offs=13) -- 2364(line=101, offs=49)
*/
ATSif(
tmp59
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2312(line=100, offs=17) -- 2314(line=100, offs=19)
*/
ATSINSmove_void(tmpret49, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2354(line=101, offs=39) -- 2363(line=101, offs=48)
*/
ATSINSmove(tmp66, ats2jspre_add_double_double(tmp58, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2333(line=101, offs=18) -- 2364(line=101, offs=49)
*/
ATSINSmove_void(tmpret49, player_setPosition_X(tmp66)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2133(line=96, offs=14) -- 2393(line=104, offs=8)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret49) ;
} /* end of [player_move] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2434(line=107, offs=20) -- 2612(line=117, offs=2)
*/
/*
local: 
global: game_tick$6$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
game_tick(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret67) ;
// ATStmpdec_void(tmp68) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2425(line=107, offs=11) -- 2612(line=117, offs=2)
*/
ATSINSflab(__patsflab_game_tick):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2447(line=109, offs=3) -- 2609(line=116, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2465(line=110, offs=14) -- 2480(line=110, offs=29)
*/
ATSINSmove_void(tmp68, enemy_update(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2529(line=112, offs=14) -- 2545(line=112, offs=30)
*/
ATSINSmove_void(tmpret67, player_update(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2447(line=109, offs=3) -- 2609(line=116, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret67) ;
} /* end of [game_tick] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2656(line=119, offs=24) -- 2698(line=122, offs=2)
*/
/*
local: 
global: player_update$7$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_update(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret69) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2643(line=119, offs=11) -- 2698(line=122, offs=2)
*/
ATSINSflab(__patsflab_player_update):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2664(line=120, offs=1) -- 2698(line=122, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2678(line=121, offs=12) -- 2695(line=121, offs=29)
*/
ATSINSmove_void(tmpret69, player_keyPress()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2664(line=120, offs=1) -- 2698(line=122, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret69) ;
} /* end of [player_update] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2745(line=124, offs=23) -- 2940(line=136, offs=4)
*/
/*
local: 
global: enemy_update$8$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
enemy_update(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret70) ;
ATStmpdec(tmp71, atstype_boxed) ;
ATStmpdec(tmp72, gameobject) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2733(line=124, offs=11) -- 2940(line=136, offs=4)
*/
ATSINSflab(__patsflab_enemy_update):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2753(line=125, offs=1) -- 2940(line=136, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2770(line=126, offs=13) -- 2782(line=126, offs=25)
*/
ATSINSmove(tmp71, enemy_get(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2791(line=128, offs=3) -- 2935(line=135, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2809(line=129, offs=5) -- 2815(line=129, offs=11)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2770(line=126, offs=13) -- 2782(line=126, offs=25)
*/
ATSifthen(ATSCKptriscons(tmp71)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2815(line=129, offs=11) -- 2815(line=129, offs=11)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2819(line=129, offs=15) -- 2821(line=129, offs=17)
*/
ATSINSmove_void(tmpret70, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2827(line=130, offs=5) -- 2833(line=130, offs=11)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2770(line=126, offs=13) -- 2782(line=126, offs=25)
*/
ATSifthen(ATSCKptrisnull(tmp71)) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2791(line=128, offs=3) -- 2935(line=135, offs=6)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2833(line=130, offs=11) -- 2833(line=130, offs=11)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2838(line=130, offs=16) -- 2935(line=135, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2859(line=131, offs=17) -- 2873(line=131, offs=31)
*/
ATSINSmove(tmp72, create_enemy()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2888(line=132, offs=14) -- 2913(line=132, offs=39)
*/
ATSINSmove_void(tmpret70, set_enemy_animation(tmp72)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2838(line=130, offs=16) -- 2935(line=135, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2753(line=125, offs=1) -- 2940(line=136, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret70) ;
} /* end of [enemy_update] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2973(line=138, offs=30) -- 3689(line=163, offs=4)
*/
/*
local: 
global: set_enemy_animation$9$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
set_enemy_animation(gameobject arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret73) ;
ATStmpdec(tmp74, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp75, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp76, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp77, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp78, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp79, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp80, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp81, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp82, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp83, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp84) ;
ATStmpdec(tmp86, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2954(line=138, offs=11) -- 3689(line=163, offs=4)
*/
ATSINSflab(__patsflab_set_enemy_animation):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2985(line=139, offs=1) -- 3689(line=163, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3008(line=140, offs=18) -- 3030(line=140, offs=40)
*/
ATSINSmove(tmp74, player_getPosition_X()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3049(line=141, offs=18) -- 3071(line=141, offs=40)
*/
ATSINSmove(tmp75, player_getPosition_Y()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3089(line=142, offs=17) -- 3114(line=142, offs=42)
*/
ATSINSmove(tmp76, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3133(line=143, offs=17) -- 3158(line=143, offs=42)
*/
ATSINSmove(tmp77, enemy_getPosition_Y(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3187(line=144, offs=27) -- 3200(line=144, offs=40)
*/
ATSINSmove(tmp79, ats2jspre_mul_double_double(tmp76, ATSPMVf0loat(1.0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3176(line=144, offs=16) -- 3200(line=144, offs=40)
*/
ATSINSmove(tmp78, ats2jspre_sub_double_double(tmp74, tmp79)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3228(line=145, offs=27) -- 3241(line=145, offs=40)
*/
ATSINSmove(tmp81, ats2jspre_mul_double_double(tmp76, ATSPMVf0loat(1.0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3217(line=145, offs=16) -- 3241(line=145, offs=40)
*/
ATSINSmove(tmp80, ats2jspre_sub_double_double(tmp74, tmp81)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3257(line=146, offs=15) -- 3272(line=146, offs=30)
*/
ATSINSmove(tmp82, ats2jspre_gt_double_double(tmp78, tmp80)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3254(line=146, offs=12) -- 3674(line=160, offs=6)
*/
ATSif(
tmp82
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3281(line=147, offs=3) -- 3454(line=153, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3304(line=148, offs=19) -- 3319(line=148, offs=34)
*/
ATSINSmove(tmp83, ats2jspre_div_double_double(tmp78, tmp80)) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3357(line=150, offs=14) -- 3369(line=150, offs=26)
*/
ATSINSmove_void(tmp84, test(tmp83)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3382(line=152, offs=5) -- 3447(line=152, offs=70)
*/
ATSINSmove_void(tmpret73, enemy_move(arg0, tmp83, ATSPMVf0loat(1.0), ATSPMVcfunlab(-1, __patsfun_10, (arg0)))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3281(line=147, offs=3) -- 3454(line=153, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3460(line=153, offs=12) -- 3674(line=160, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3483(line=154, offs=19) -- 3498(line=154, offs=34)
*/
ATSINSmove(tmp86, ats2jspre_div_double_double(tmp80, tmp78)) ;

/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3563(line=158, offs=5) -- 3628(line=158, offs=70)
*/
ATSINSmove_void(tmpret73, enemy_move(arg0, ATSPMVf0loat(1.0), tmp86, ATSPMVcfunlab(-1, __patsfun_11, (arg0)))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3460(line=153, offs=12) -- 3674(line=160, offs=6)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2985(line=139, offs=1) -- 3689(line=163, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret73) ;
} /* end of [set_enemy_animation] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3418(line=152, offs=41) -- 3446(line=152, offs=69)
*/
/*
local: 
global: __patsfun_10$0(level=1)
local: enemy$172(1)(HSEcst(gameobject))
global: enemy$172(1)(HSEcst(gameobject))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_10(gameobject env0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret85) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3418(line=152, offs=41) -- 3446(line=152, offs=69)
*/
ATSINSflab(__patsflab___patsfun_10):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3427(line=152, offs=50) -- 3445(line=152, offs=68)
*/
ATSINSmove_void(tmpret85, enemy_remove(env0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret85) ;
} /* end of [__patsfun_10] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3599(line=158, offs=41) -- 3627(line=158, offs=69)
*/
/*
local: 
global: __patsfun_11$0(level=1)
local: enemy$172(1)(HSEcst(gameobject))
global: enemy$172(1)(HSEcst(gameobject))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_11(gameobject env0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret87) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3599(line=158, offs=41) -- 3627(line=158, offs=69)
*/
ATSINSflab(__patsflab___patsfun_11):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3608(line=158, offs=50) -- 3626(line=158, offs=68)
*/
ATSINSmove_void(tmpret87, enemy_remove(env0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret87) ;
} /* end of [__patsfun_11] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3715(line=166, offs=21) -- 4329(line=184, offs=4)
*/
/*
local: 
global: enemy_move$12$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
enemy_move(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2, atstype_cloptr arg3)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret88) ;
ATStmpdec(tmp89, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp90, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp91, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp92, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp93) ;
ATStmpdec(tmp94, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp95, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3705(line=166, offs=11) -- 4329(line=184, offs=4)
*/
ATSINSflab(__patsflab_enemy_move):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3748(line=167, offs=1) -- 4329(line=184, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3769(line=168, offs=17) -- 3794(line=168, offs=42)
*/
ATSINSmove(tmp89, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3813(line=169, offs=17) -- 3838(line=169, offs=42)
*/
ATSINSmove(tmp90, enemy_getPosition_Y(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3857(line=170, offs=17) -- 3874(line=170, offs=34)
*/
ATSINSmove(tmp91, ats2jspre_add_double_double(tmp89, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3892(line=171, offs=17) -- 3909(line=171, offs=34)
*/
ATSINSmove(tmp92, ats2jspre_add_double_double(tmp90, arg2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3922(line=172, offs=12) -- 3964(line=172, offs=54)
*/
ATSINSmove_void(tmp93, enemy_setPosition(arg0, tmp91, tmp92)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3980(line=173, offs=15) -- 4022(line=173, offs=57)
*/
ATSINSmove(tmp94, enemy_check_crash(arg0, tmp91, tmp92)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4030(line=175, offs=3) -- 4324(line=183, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4050(line=176, offs=5) -- 4051(line=176, offs=6)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3980(line=173, offs=15) -- 4022(line=173, offs=57)
*/
ATSifnthen(ATSCKpat_int(tmp94, ATSPMVint(1))) { ATSINSgoto(__atstmplab6) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4051(line=176, offs=6) -- 4051(line=176, offs=6)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4055(line=176, offs=10) -- 4058(line=176, offs=13)
*/
ATSINSmove_void(tmpret88, ATSfunclo_clo(arg3, (atstype_cloptr), atsvoid_t0ype)(arg3)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4071(line=177, offs=5) -- 4072(line=177, offs=6)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3980(line=173, offs=15) -- 4022(line=173, offs=57)
*/
ATSifnthen(ATSCKpat_int(tmp94, ATSPMVint(0))) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4030(line=175, offs=3) -- 4324(line=183, offs=6)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4072(line=177, offs=6) -- 4072(line=177, offs=6)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4076(line=177, offs=10) -- 4324(line=183, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4115(line=178, offs=23) -- 4157(line=178, offs=65)
*/
ATSINSmove(tmp95, enemy_check_bound(arg0, tmp91, tmp92)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4169(line=180, offs=5) -- 4312(line=182, offs=85)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4197(line=181, offs=7) -- 4198(line=181, offs=8)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4115(line=178, offs=23) -- 4157(line=178, offs=65)
*/
ATSifnthen(ATSCKpat_int(tmp95, ATSPMVint(1))) { ATSINSgoto(__atstmplab10) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4198(line=181, offs=8) -- 4198(line=181, offs=8)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4202(line=181, offs=12) -- 4220(line=181, offs=30)
*/
ATSINSmove_void(tmpret88, enemy_remove(arg0)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4234(line=182, offs=7) -- 4235(line=182, offs=8)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4115(line=178, offs=23) -- 4157(line=178, offs=65)
*/
ATSifnthen(ATSCKpat_int(tmp95, ATSPMVint(0))) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4169(line=180, offs=5) -- 4312(line=182, offs=85)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4235(line=182, offs=8) -- 4235(line=182, offs=8)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4239(line=182, offs=12) -- 4312(line=182, offs=85)
*/
ATSINSmove_void(tmpret88, setTimeout_cloref(ATSPMVcfunlab(-1, __patsfun_13, (arg0, arg1, arg2, arg3)), ATSPMVf0loat(5.0))) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4076(line=177, offs=10) -- 4324(line=183, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3748(line=167, offs=1) -- 4329(line=184, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret88) ;
} /* end of [enemy_move] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4257(line=182, offs=30) -- 4306(line=182, offs=79)
*/
/*
local: 
global: __patsfun_13$0(level=1)
local: enemy$183(1)(HSEcst(gameobject)), speed_x$184(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), speed_y$185(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), k$186(1)(HSEfun(; HSEcst(atsvoid_t0ype)))
global: enemy$183(1)(HSEcst(gameobject)), speed_x$184(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), speed_y$185(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), k$186(1)(HSEfun(; HSEcst(atsvoid_t0ype)))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_13(gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret96) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4257(line=182, offs=30) -- 4306(line=182, offs=79)
*/
ATSINSflab(__patsflab___patsfun_13):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4267(line=182, offs=40) -- 4305(line=182, offs=78)
*/
ATSINSmove_void(tmpret96, enemy_move(env0, env1, env2, env3)) ;

ATSfunbody_end()
ATSreturn_void(tmpret96) ;
} /* end of [__patsfun_13] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4360(line=186, offs=28) -- 4634(line=194, offs=4)
*/
/*
local: 
global: enemy_check_crash$14$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_crash(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret97, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp98, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp99, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp100, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp101, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp102, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp103, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4343(line=186, offs=11) -- 4634(line=194, offs=4)
*/
ATSINSflab(__patsflab_enemy_check_crash):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4388(line=186, offs=56) -- 4634(line=194, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4410(line=187, offs=18) -- 4432(line=187, offs=40)
*/
ATSINSmove(tmp98, player_getPosition_X()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4451(line=188, offs=18) -- 4473(line=188, offs=40)
*/
ATSINSmove(tmp99, player_getPosition_Y()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4491(line=189, offs=17) -- 4516(line=189, offs=42)
*/
ATSINSmove(tmp100, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4535(line=190, offs=17) -- 4560(line=190, offs=42)
*/
ATSINSmove(tmp101, enemy_getPosition_Y(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4572(line=192, offs=6) -- 4612(line=192, offs=46)
*/
ATSINSmove(tmp103, ats2jspre_eq_double_double(tmp98, tmp100)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4572(line=192, offs=6) -- 4612(line=192, offs=46)
*/
ATSif(
tmp103
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4572(line=192, offs=6) -- 4612(line=192, offs=46)
*/
ATSINSmove(tmp102, ats2jspre_eq_double_double(tmp99, tmp101)) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4572(line=192, offs=6) -- 4612(line=192, offs=46)
*/
ATSINSmove(tmp102, ATSPMVbool_false()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4569(line=192, offs=3) -- 4629(line=193, offs=9)
*/
ATSif(
tmp102
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4618(line=192, offs=52) -- 4619(line=192, offs=53)
*/
ATSINSmove(tmpret97, ATSPMVi0nt(1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4628(line=193, offs=8) -- 4629(line=193, offs=9)
*/
ATSINSmove(tmpret97, ATSPMVi0nt(0)) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4388(line=186, offs=56) -- 4634(line=194, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret97) ;
} /* end of [enemy_check_crash] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4665(line=196, offs=28) -- 4800(line=198, offs=9)
*/
/*
local: 
global: enemy_check_bound$15$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_bound(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret104, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp105, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp106, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp107, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp108, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4648(line=196, offs=11) -- 4800(line=198, offs=9)
*/
ATSINSflab(__patsflab_enemy_check_bound):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSINSmove(tmp108, ats2jspre_gt_double_double(arg1, ATSPMVfloat(400.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSif(
tmp108
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSINSmove(tmp107, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSINSmove(tmp107, ats2jspre_lt_double_double(arg1, ATSPMVf0loat(0.0))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSif(
tmp107
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSINSmove(tmp106, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSINSmove(tmp106, ats2jspre_gt_double_double(arg2, ATSPMVfloat(500.000000000000000000))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSif(
tmp106
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSINSmove(tmp105, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4700(line=197, offs=6) -- 4783(line=197, offs=89)
*/
ATSINSmove(tmp105, ats2jspre_lt_double_double(arg2, ATSPMVf0loat(0.0))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4697(line=197, offs=3) -- 4800(line=198, offs=9)
*/
ATSif(
tmp105
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4789(line=197, offs=95) -- 4790(line=197, offs=96)
*/
ATSINSmove(tmpret104, ATSPMVi0nt(1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4799(line=198, offs=8) -- 4800(line=198, offs=9)
*/
ATSINSmove(tmpret104, ATSPMVi0nt(0)) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret104) ;
} /* end of [enemy_check_bound] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 328(line=22, offs=16) -- 339(line=22, offs=27)
*/
ATSINSmove(statmp0, ats2jspre_ref(ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 364(line=23, offs=24) -- 375(line=23, offs=35)
*/
ATSINSmove(statmp1, ats2jspre_ref(ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 387(line=24, offs=11) -- 399(line=24, offs=23)
*/
ATSINSmove(statmp2, store_init()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 417(line=25, offs=17) -- 429(line=25, offs=29)
*/
ATSINSmove(statmp3, ats2jspre_ref(statmp2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 451(line=26, offs=20) -- 470(line=26, offs=39)
*/
ATSINSmove(statmp4, ats2jspre_ref(ATSPMVintrep(2000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 488(line=27, offs=16) -- 500(line=27, offs=28)
*/
ATSINSmove(statmp5, ats2jspre_ref(ATSPMVi0nt(10))) ;

/* (*nothing*) */
/* in of [local] */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1401(line=71, offs=12) -- 1407(line=71, offs=18)
*/
ATSINSmove_void(statmp34, init_0()) ;

/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
ATSextern()
atsvoid_t0ype
my_dynload()
{
ATSfunbody_beg()
ATSINSmove_void(tmpret_void, _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynload()) ;
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} // end-of-dynload-alias
/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4804(line=200, offs=1) -- 5015(line=217, offs=3)
*/
ATSextcode_beg()
function
ATS_start()
{
  var _ = my_dynload();
}

function
test(x){
  alert(x);
}

function
setTimeout_cloref(fwork, ntime)
{
  setTimeout(function(){cloref_app(fwork);return;}, ntime);
}
ATSextcode_end()

/* ****** ****** */

/* end-of-compilation-unit */
