/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-4-28: 22h:51m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
/cs/coursedata/cs520/ATS2-017/libc/SATS/math.sats: 1380(line=35, offs=1) -- 1417(line=37, offs=3)
*/

#include "libc/CATS/math.cats"
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/list.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 357(line=27, offs=1) -- 396(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 423(line=32, offs=1) -- 455(line=32, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 482(line=36, offs=1) -- 512(line=36, offs=31)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/print.sats: 189(line=14, offs=1) -- 218(line=14, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 513(line=37, offs=1) -- 545(line=37, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/filebas.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/list.dats: 572(line=41, offs=1) -- 601(line=41, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/list.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/option.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 359(line=27, offs=1) -- 398(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 425(line=32, offs=1) -- 457(line=32, offs=33)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/option.dats: 484(line=36, offs=1) -- 515(line=36, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/option.sats: 262(line=21, offs=1) -- 291(line=21, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 359(line=27, offs=1) -- 398(line=28, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 425(line=32, offs=1) -- 457(line=33, offs=25)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 461(line=35, offs=1) -- 491(line=35, offs=31)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/print.sats: 189(line=14, offs=1) -- 218(line=14, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/DATS/stream.dats: 516(line=39, offs=1) -- 547(line=39, offs=32)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/reference.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSmath.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSdate.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSarray.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
/cs/coursedata/cs520/ATS2-017/contrib/libatscc/libatscc2js/SATS/JSglobal.sats: 200(line=16, offs=1) -- 229(line=16, offs=30)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(ats2jspre_ref)
ATSdyncst_mac(ats2jspre_ref_set_elt)
ATSdyncst_mac(player_init)
ATSdyncst_mac(ats2jspre_gt_int0_int0)
ATSdyncst_mac(ats2jspre_ref_get_elt)
ATSdyncst_mac(ats2jspre_sub_int0_int0)
ATSdyncst_mac(update_lives)
ATSdyncst_mac(gameover)
ATSdyncst_mac(ats2jspre_lte_int0_int0)
ATSdyncst_mac(ats2jspre_add_int0_int0)
ATSdyncst_mac(ats2jspre_eq_int0_int0)
ATSdyncst_mac(check_key)
ATSdyncst_mac(player_move)
ATSdyncst_mac(ats2jspre_neg_double)
ATSdyncst_mac(ats2jspre_eq_double_double)
ATSdyncst_mac(player_getPosition_Y)
ATSdyncst_mac(ats2jspre_gt_double_double)
ATSdyncst_mac(ats2jspre_add_double_double)
ATSdyncst_mac(ats2jspre_lte_double_double)
ATSdyncst_mac(ats2jspre_div_double_double)
ATSdyncst_mac(player_setPosition_Y)
ATSdyncst_mac(player_getPosition_X)
ATSdyncst_mac(ats2jspre_sub_double_double)
ATSdyncst_mac(ats2jspre_div_double_int)
ATSdyncst_mac(ats2jspre_lt_double_double)
ATSdyncst_mac(player_setPosition_X)
ATSdyncst_mac(enemy_update)
ATSdyncst_mac(score_update)
ATSdyncst_mac(player_update)
ATSdyncst_mac(player_keyPress)
ATSdyncst_mac(enemy_get)
ATSdyncst_mac(create_enemy)
ATSdyncst_mac(set_enemy_animation)
ATSdyncst_mac(enemy_getPosition_X)
ATSdyncst_mac(enemy_getPosition_Y)
ATSdyncst_mac(calc_speed_x)
ATSdyncst_mac(ats2jspre_mul_double_double)
ATSdyncst_mac(enemy_move)
ATSdyncst_mac(player_crash)
ATSdyncst_mac(enemy_remove)
ATSdyncst_extfun(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get, (), atstype_boxed) ;
ATSdyncst_mac(enemy_setPosition)
ATSdyncst_mac(enemy_check_crash)
ATSdyncst_mac(enemy_check_bound)
ATSdyncst_mac(setTimeout_cloref)
ATSdyncst_mac(calc_dist)
ATSdyncst_mac(crash_report)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatmpdec(statmp0, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp1, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp2, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp3, atstkind_type(atstype_ptrk)) ;
#if(0)
ATSextern()
atsvoid_t0ype
init() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
enemy_get(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
enemy_move_get(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_keyPress() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_move(atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
game_tick(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
player_update(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
enemy_update(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
set_enemy_animation(gameobject) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
__patsfun_10(gameobject) ;

#if(0)
ATSextern()
atsvoid_t0ype
player_crash(gameobject) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
enemy_move(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
__patsfun_13(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_funptr) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_crash(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_bound(gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
cloref_app(atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSclosurerize_beg(__patsfun_10, (gameobject), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
gameobject env0 ;
} __patsfun_10__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_10__cfun
(
__patsfun_10__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_10(p_cenv->env0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_10__closureinit
(
__patsfun_10__closure_t0ype *p_cenv, gameobject env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_10__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_10__closurerize
(
gameobject env0
)
{
return __patsfun_10__closureinit(ATS_MALLOC(sizeof(__patsfun_10__closure_t0ype)), env0) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(__patsfun_13, (gameobject, atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double), atstype_funptr), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
gameobject env0 ;
atstkind_t0ype(atstype_double) env1 ;
atstkind_t0ype(atstype_double) env2 ;
atstype_funptr env3 ;
} __patsfun_13__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_13__cfun
(
__patsfun_13__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_13(p_cenv->env0, p_cenv->env1, p_cenv->env2, p_cenv->env3)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_13__closureinit
(
__patsfun_13__closure_t0ype *p_cenv, gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->env2 = env2 ;
p_cenv->env3 = env3 ;
p_cenv->cfun = __patsfun_13__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_13__closurerize
(
gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3
)
{
return __patsfun_13__closureinit(ATS_MALLOC(sizeof(__patsfun_13__closure_t0ype)), env0, env1, env2, env3) ;
} /* end of [closurerize] */
ATSclosurerize_end()
/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 523(line=29, offs=17) -- 619(line=34, offs=4)
*/
/*
local: 
global: init$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
init()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret4) ;
// ATStmpdec_void(tmp5) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 519(line=29, offs=13) -- 619(line=34, offs=4)
*/
ATSINSflab(__patsflab_init):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 537(line=30, offs=3) -- 619(line=34, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 573(line=32, offs=14) -- 586(line=32, offs=27)
*/
ATSINSmove_void(tmp5, ats2jspre_ref_set_elt(statmp0, ATSPMVi0nt(3))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 601(line=33, offs=14) -- 614(line=33, offs=27)
*/
ATSINSmove_void(tmpret4, player_init()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 537(line=30, offs=3) -- 619(line=34, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret4) ;
} /* end of [init] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 645(line=36, offs=23) -- 869(line=46, offs=8)
*/
/*
local: 
global: player_get$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret6, atstype_boxed) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp9) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp12) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp14) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 635(line=36, offs=13) -- 869(line=46, offs=8)
*/
ATSINSflab(__patsflab_player_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 659(line=37, offs=8) -- 667(line=37, offs=16)
*/
ATSINSmove(tmp8, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 659(line=37, offs=8) -- 671(line=37, offs=20)
*/
ATSINSmove(tmp7, ats2jspre_gt_int0_int0(tmp8, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 656(line=37, offs=5) -- 869(line=46, offs=8)
*/
ATSif(
tmp7
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 677(line=37, offs=26) -- 798(line=42, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 710(line=38, offs=29) -- 718(line=38, offs=37)
*/
ATSINSmove(tmp11, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 710(line=38, offs=29) -- 722(line=38, offs=41)
*/
ATSINSmove(tmp10, ats2jspre_sub_int0_int0(tmp11, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 698(line=38, offs=17) -- 722(line=38, offs=41)
*/
ATSINSmove_void(tmp9, ats2jspre_ref_set_elt(statmp0, tmp10)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 754(line=39, offs=31) -- 762(line=39, offs=39)
*/
ATSINSmove(tmp13, ats2jspre_ref_get_elt(statmp0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 741(line=39, offs=18) -- 763(line=39, offs=40)
*/
ATSINSmove_void(tmp12, update_lives(tmp13)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 782(line=41, offs=9) -- 789(line=41, offs=16)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret6, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret6, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret6, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 677(line=37, offs=26) -- 798(line=42, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 804(line=42, offs=14) -- 869(line=46, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 826(line=43, offs=18) -- 836(line=43, offs=28)
*/
ATSINSmove_void(tmp14, gameover()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 854(line=45, offs=9) -- 860(line=45, offs=15)
*/

ATSINSmove_nil(tmpret6) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 804(line=42, offs=14) -- 869(line=46, offs=8)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret6) ;
} /* end of [_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 894(line=48, offs=22) -- 1104(line=57, offs=6)
*/
/*
local: 
global: enemy_get$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
enemy_get(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstype_boxed) ;
// ATStmpdec_void(tmp16) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp21) ;
ATStmpdec(tmp22, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 885(line=48, offs=13) -- 1104(line=57, offs=6)
*/
ATSINSflab(__patsflab_enemy_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 901(line=48, offs=29) -- 1104(line=57, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 935(line=49, offs=30) -- 947(line=49, offs=42)
*/
ATSINSmove(tmp18, ats2jspre_ref_get_elt(statmp2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 935(line=49, offs=30) -- 952(line=49, offs=47)
*/
ATSINSmove(tmp17, ats2jspre_sub_int0_int0(tmp18, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 919(line=49, offs=14) -- 952(line=49, offs=47)
*/
ATSINSmove_void(tmp16, ats2jspre_ref_set_elt(statmp2, tmp17)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 967(line=51, offs=8) -- 979(line=51, offs=20)
*/
ATSINSmove(tmp20, ats2jspre_ref_get_elt(statmp2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 967(line=51, offs=8) -- 984(line=51, offs=25)
*/
ATSINSmove(tmp19, ats2jspre_lte_int0_int0(tmp20, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 964(line=51, offs=5) -- 1097(line=56, offs=20)
*/
ATSif(
tmp19
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 990(line=51, offs=31) -- 1085(line=56, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1028(line=53, offs=32) -- 1040(line=53, offs=44)
*/
ATSINSmove(tmp23, ats2jspre_ref_get_elt(statmp2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1028(line=53, offs=32) -- 1053(line=53, offs=57)
*/
ATSINSmove(tmp22, ats2jspre_add_int0_int0(tmp23, ATSPMVintrep(100))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1012(line=53, offs=16) -- 1053(line=53, offs=57)
*/
ATSINSmove_void(tmp21, ats2jspre_ref_set_elt(statmp2, tmp22)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1069(line=55, offs=7) -- 1076(line=55, offs=14)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret15, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret15, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret15, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 990(line=51, offs=31) -- 1085(line=56, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1091(line=56, offs=14) -- 1097(line=56, offs=20)
*/

ATSINSmove_nil(tmpret15) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 901(line=48, offs=29) -- 1104(line=57, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret15) ;
} /* end of [enemy_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1134(line=59, offs=27) -- 1312(line=67, offs=6)
*/
/*
local: 
global: enemy_move_get$3$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
enemy_move_get(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24, atstype_boxed) ;
// ATStmpdec_void(tmp25) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp27, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp30) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1120(line=59, offs=13) -- 1312(line=67, offs=6)
*/
ATSINSflab(__patsflab_enemy_move_get):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1141(line=59, offs=34) -- 1312(line=67, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1171(line=60, offs=26) -- 1179(line=60, offs=34)
*/
ATSINSmove(tmp27, ats2jspre_ref_get_elt(statmp3)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1171(line=60, offs=26) -- 1184(line=60, offs=39)
*/
ATSINSmove(tmp26, ats2jspre_sub_int0_int0(tmp27, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1159(line=60, offs=14) -- 1184(line=60, offs=39)
*/
ATSINSmove_void(tmp25, ats2jspre_ref_set_elt(statmp3, tmp26)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1199(line=62, offs=8) -- 1207(line=62, offs=16)
*/
ATSINSmove(tmp29, ats2jspre_ref_get_elt(statmp3)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1199(line=62, offs=8) -- 1212(line=62, offs=21)
*/
ATSINSmove(tmp28, ats2jspre_lte_int0_int0(tmp29, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1196(line=62, offs=5) -- 1305(line=66, offs=20)
*/
ATSif(
tmp28
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1218(line=62, offs=27) -- 1293(line=66, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1250(line=63, offs=28) -- 1258(line=63, offs=36)
*/
ATSINSmove(tmp32, ats2jspre_ref_get_elt(statmp3)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1250(line=63, offs=28) -- 1263(line=63, offs=41)
*/
ATSINSmove(tmp31, ats2jspre_add_int0_int0(tmp32, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1238(line=63, offs=16) -- 1263(line=63, offs=41)
*/
ATSINSmove_void(tmp30, ats2jspre_ref_set_elt(statmp3, tmp31)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1277(line=65, offs=5) -- 1284(line=65, offs=12)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret24, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret24, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret24, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1218(line=62, offs=27) -- 1293(line=66, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1299(line=66, offs=14) -- 1305(line=66, offs=20)
*/

ATSINSmove_nil(tmpret24) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1141(line=59, offs=34) -- 1312(line=67, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret24) ;
} /* end of [enemy_move_get] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1384(line=72, offs=26) -- 1718(line=82, offs=2)
*/
/*
local: 
global: player_keyPress$4$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_keyPress()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret33) ;
// ATStmpdec_void(tmp34) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp37, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp38) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp41) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp43, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp46, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1369(line=72, offs=11) -- 1718(line=82, offs=2)
*/
ATSINSflab(__patsflab_player_keyPress):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1391(line=73, offs=1) -- 1718(line=82, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1413(line=75, offs=8) -- 1431(line=75, offs=26)
*/
ATSINSmove(tmp36, check_key(ATSPMVintrep(37))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1413(line=75, offs=8) -- 1436(line=75, offs=31)
*/
ATSINSmove(tmp35, ats2jspre_eq_int0_int0(tmp36, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1410(line=75, offs=5) -- 1473(line=75, offs=68)
*/
ATSif(
tmp35
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1454(line=75, offs=49) -- 1467(line=75, offs=62)
*/
ATSINSmove(tmp37, ats2jspre_neg_double(ATSPMVfloat(20.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1442(line=75, offs=37) -- 1473(line=75, offs=68)
*/
ATSINSmove_void(tmp34, player_move(tmp37, ATSPMVf0loat(0.0))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1473(line=75, offs=68) -- 1473(line=75, offs=68)
*/
ATSINSmove_void(tmp34, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1494(line=77, offs=8) -- 1513(line=77, offs=27)
*/
ATSINSmove(tmp40, check_key(ATSPMVintrep(39))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1494(line=77, offs=8) -- 1518(line=77, offs=32)
*/
ATSINSmove(tmp39, ats2jspre_eq_int0_int0(tmp40, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1491(line=77, offs=5) -- 1554(line=77, offs=68)
*/
ATSif(
tmp39
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1524(line=77, offs=38) -- 1554(line=77, offs=68)
*/
ATSINSmove_void(tmp38, player_move(ATSPMVfloat(20.000000000000000000), ATSPMVf0loat(0.0))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1554(line=77, offs=68) -- 1554(line=77, offs=68)
*/
ATSINSmove_void(tmp38, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1575(line=79, offs=8) -- 1591(line=79, offs=24)
*/
ATSINSmove(tmp43, check_key(ATSPMVintrep(38))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1575(line=79, offs=8) -- 1596(line=79, offs=29)
*/
ATSINSmove(tmp42, ats2jspre_eq_int0_int0(tmp43, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1572(line=79, offs=5) -- 1633(line=79, offs=66)
*/
ATSif(
tmp42
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1602(line=79, offs=35) -- 1633(line=79, offs=66)
*/
ATSINSmove_void(tmp41, player_move(ATSPMVf0loat(0.0), ATSPMVfloat(20.000000000000000000))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1633(line=79, offs=66) -- 1633(line=79, offs=66)
*/
ATSINSmove_void(tmp41, ATSPMVempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1654(line=81, offs=8) -- 1672(line=81, offs=26)
*/
ATSINSmove(tmp45, check_key(ATSPMVintrep(40))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1654(line=81, offs=8) -- 1677(line=81, offs=31)
*/
ATSINSmove(tmp44, ats2jspre_eq_int0_int0(tmp45, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1651(line=81, offs=5) -- 1715(line=81, offs=69)
*/
ATSif(
tmp44
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1701(line=81, offs=55) -- 1714(line=81, offs=68)
*/
ATSINSmove(tmp46, ats2jspre_neg_double(ATSPMVfloat(20.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1683(line=81, offs=37) -- 1715(line=81, offs=69)
*/
ATSINSmove_void(tmpret33, player_move(ATSPMVf0loat(0.0), tmp46)) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1715(line=81, offs=69) -- 1715(line=81, offs=69)
*/
ATSINSmove_void(tmpret33, ATSPMVempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1391(line=73, offs=1) -- 1718(line=82, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret33) ;
} /* end of [player_keyPress] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1766(line=84, offs=22) -- 2326(line=103, offs=2)
*/
/*
local: 
global: player_move$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_move(atstkind_t0ype(atstype_double) arg0, atstkind_t0ype(atstype_double) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret47) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp49, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp50, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp52, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp53, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp54, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp55, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp56, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp57, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp58, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp59, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp60, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp61, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp62, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp63, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp64, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1755(line=84, offs=11) -- 2326(line=103, offs=2)
*/
ATSINSflab(__patsflab_player_move):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1788(line=86, offs=8) -- 1795(line=86, offs=15)
*/
ATSINSmove(tmp48, ats2jspre_eq_double_double(arg0, ATSPMVf0loat(0.0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1785(line=86, offs=5) -- 2323(line=102, offs=8)
*/
ATSif(
tmp48
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1801(line=86, offs=21) -- 2057(line=94, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1834(line=87, offs=21) -- 1856(line=87, offs=43)
*/
ATSINSmove(tmp49, player_getPosition_Y()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1892(line=89, offs=16) -- 1953(line=89, offs=77)
*/
ATSINSmove(tmp52, ats2jspre_add_double_double(tmp49, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1892(line=89, offs=16) -- 1953(line=89, offs=77)
*/
ATSINSmove(tmp51, ats2jspre_gt_double_double(tmp52, ATSPMVfloat(500.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1892(line=89, offs=16) -- 1953(line=89, offs=77)
*/
ATSif(
tmp51
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1892(line=89, offs=16) -- 1953(line=89, offs=77)
*/
ATSINSmove(tmp50, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1892(line=89, offs=16) -- 1953(line=89, offs=77)
*/
ATSINSmove(tmp53, ats2jspre_add_double_double(tmp49, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1892(line=89, offs=16) -- 1953(line=89, offs=77)
*/
ATSINSmove(tmp54, ats2jspre_div_double_double(ATSPMVfloat(18.000000000000000000), ATSPMVf0loat(2.0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1892(line=89, offs=16) -- 1953(line=89, offs=77)
*/
ATSINSmove(tmp50, ats2jspre_lte_double_double(tmp53, tmp54)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1889(line=89, offs=13) -- 2028(line=91, offs=49)
*/
ATSif(
tmp50
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1976(line=90, offs=17) -- 1978(line=90, offs=19)
*/
ATSINSmove_void(tmpret47, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2018(line=91, offs=39) -- 2027(line=91, offs=48)
*/
ATSINSmove(tmp55, ats2jspre_add_double_double(tmp49, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1997(line=91, offs=18) -- 2028(line=91, offs=49)
*/
ATSINSmove_void(tmpret47, player_setPosition_Y(tmp55)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 1801(line=86, offs=21) -- 2057(line=94, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2063(line=94, offs=14) -- 2323(line=102, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2088(line=95, offs=21) -- 2110(line=95, offs=43)
*/
ATSINSmove(tmp56, player_getPosition_X()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSINSmove(tmp59, ats2jspre_add_double_double(tmp56, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSINSmove(tmp61, ats2jspre_div_double_int(ATSPMVfloat(18.000000000000000000), ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSINSmove(tmp60, ats2jspre_sub_double_double(ATSPMVfloat(400.000000000000000000), tmp61)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSINSmove(tmp58, ats2jspre_gt_double_double(tmp59, tmp60)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSif(
tmp58
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSINSmove(tmp57, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSINSmove(tmp62, ats2jspre_add_double_double(tmp56, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSINSmove(tmp63, ats2jspre_div_double_int(ATSPMVfloat(18.000000000000000000), ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2146(line=97, offs=16) -- 2219(line=97, offs=89)
*/
ATSINSmove(tmp57, ats2jspre_lt_double_double(tmp62, tmp63)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2143(line=97, offs=13) -- 2294(line=99, offs=49)
*/
ATSif(
tmp57
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2242(line=98, offs=17) -- 2244(line=98, offs=19)
*/
ATSINSmove_void(tmpret47, ATSPMVempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2284(line=99, offs=39) -- 2293(line=99, offs=48)
*/
ATSINSmove(tmp64, ats2jspre_add_double_double(tmp56, arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2263(line=99, offs=18) -- 2294(line=99, offs=49)
*/
ATSINSmove_void(tmpret47, player_setPosition_X(tmp64)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2063(line=94, offs=14) -- 2323(line=102, offs=8)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret47) ;
} /* end of [player_move] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2364(line=105, offs=20) -- 2540(line=115, offs=2)
*/
/*
local: 
global: game_tick$6$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
game_tick(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret65) ;
// ATStmpdec_void(tmp66) ;
// ATStmpdec_void(tmp67) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2355(line=105, offs=11) -- 2540(line=115, offs=2)
*/
ATSINSflab(__patsflab_game_tick):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2377(line=107, offs=3) -- 2537(line=114, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2395(line=108, offs=14) -- 2410(line=108, offs=29)
*/
ATSINSmove_void(tmp66, enemy_update(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2426(line=109, offs=14) -- 2441(line=109, offs=29)
*/
ATSINSmove_void(tmp67, score_update(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2457(line=110, offs=14) -- 2473(line=110, offs=30)
*/
ATSINSmove_void(tmpret65, player_update(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2377(line=107, offs=3) -- 2537(line=114, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret65) ;
} /* end of [game_tick] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2584(line=117, offs=24) -- 2626(line=120, offs=2)
*/
/*
local: 
global: player_update$7$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_update(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret68) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2571(line=117, offs=11) -- 2626(line=120, offs=2)
*/
ATSINSflab(__patsflab_player_update):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2592(line=118, offs=1) -- 2626(line=120, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2606(line=119, offs=12) -- 2623(line=119, offs=29)
*/
ATSINSmove_void(tmpret68, player_keyPress()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2592(line=118, offs=1) -- 2626(line=120, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret68) ;
} /* end of [player_update] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2673(line=122, offs=23) -- 2868(line=134, offs=4)
*/
/*
local: 
global: enemy_update$8$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
enemy_update(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret69) ;
ATStmpdec(tmp70, atstype_boxed) ;
ATStmpdec(tmp71, gameobject) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2661(line=122, offs=11) -- 2868(line=134, offs=4)
*/
ATSINSflab(__patsflab_enemy_update):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2681(line=123, offs=1) -- 2868(line=134, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2698(line=124, offs=13) -- 2710(line=124, offs=25)
*/
ATSINSmove(tmp70, enemy_get(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2719(line=126, offs=3) -- 2863(line=133, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2737(line=127, offs=5) -- 2743(line=127, offs=11)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2698(line=124, offs=13) -- 2710(line=124, offs=25)
*/
ATSifthen(ATSCKptriscons(tmp70)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2743(line=127, offs=11) -- 2743(line=127, offs=11)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2747(line=127, offs=15) -- 2749(line=127, offs=17)
*/
ATSINSmove_void(tmpret69, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2755(line=128, offs=5) -- 2761(line=128, offs=11)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2698(line=124, offs=13) -- 2710(line=124, offs=25)
*/
ATSifthen(ATSCKptrisnull(tmp70)) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2719(line=126, offs=3) -- 2863(line=133, offs=6)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2761(line=128, offs=11) -- 2761(line=128, offs=11)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2766(line=128, offs=16) -- 2863(line=133, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2787(line=129, offs=17) -- 2801(line=129, offs=31)
*/
ATSINSmove(tmp71, create_enemy()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2816(line=130, offs=14) -- 2841(line=130, offs=39)
*/
ATSINSmove_void(tmpret69, set_enemy_animation(tmp71)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2766(line=128, offs=16) -- 2863(line=133, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2681(line=123, offs=1) -- 2868(line=134, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret69) ;
} /* end of [enemy_update] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2901(line=136, offs=30) -- 3338(line=149, offs=4)
*/
/*
local: 
global: set_enemy_animation$9$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
set_enemy_animation(gameobject arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret72) ;
ATStmpdec(tmp73, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp74, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp75, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp76, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp77, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp78, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp79, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp80, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp81, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2882(line=136, offs=11) -- 3338(line=149, offs=4)
*/
ATSINSflab(__patsflab_set_enemy_animation):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2913(line=137, offs=1) -- 3338(line=149, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2936(line=138, offs=18) -- 2958(line=138, offs=40)
*/
ATSINSmove(tmp73, player_getPosition_X()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2977(line=139, offs=18) -- 2999(line=139, offs=40)
*/
ATSINSmove(tmp74, player_getPosition_Y()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3017(line=140, offs=17) -- 3042(line=140, offs=42)
*/
ATSINSmove(tmp75, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3061(line=141, offs=17) -- 3086(line=141, offs=42)
*/
ATSINSmove(tmp76, enemy_getPosition_Y(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3104(line=142, offs=16) -- 3122(line=142, offs=34)
*/
ATSINSmove(tmp77, ats2jspre_sub_double_double(tmp73, tmp75)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3139(line=143, offs=16) -- 3157(line=143, offs=34)
*/
ATSINSmove(tmp78, ats2jspre_sub_double_double(tmp74, tmp76)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3173(line=144, offs=15) -- 3188(line=144, offs=30)
*/
ATSINSmove(tmp79, ats2jspre_div_double_double(tmp77, tmp78)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3206(line=145, offs=17) -- 3224(line=145, offs=35)
*/
ATSINSmove(tmp80, calc_speed_x(tmp79)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3243(line=146, offs=17) -- 3258(line=146, offs=32)
*/
ATSINSmove(tmp81, ats2jspre_mul_double_double(tmp79, tmp80)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3268(line=148, offs=5) -- 3333(line=148, offs=70)
*/
ATSINSmove_void(tmpret72, enemy_move(arg0, tmp80, tmp81, ATSPMVcfunlab(-1, __patsfun_10, (arg0)))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 2913(line=137, offs=1) -- 3338(line=149, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret72) ;
} /* end of [set_enemy_animation] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3304(line=148, offs=41) -- 3332(line=148, offs=69)
*/
/*
local: 
global: __patsfun_10$0(level=1)
local: enemy$185(1)(HSEcst(gameobject))
global: enemy$185(1)(HSEcst(gameobject))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_10(gameobject env0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret82) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3304(line=148, offs=41) -- 3332(line=148, offs=69)
*/
ATSINSflab(__patsflab___patsfun_10):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3313(line=148, offs=50) -- 3331(line=148, offs=68)
*/
ATSINSmove_void(tmpret82, player_crash(env0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret82) ;
} /* end of [__patsfun_10] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3364(line=151, offs=23) -- 3538(line=158, offs=4)
*/
/*
local: 
global: player_crash$11$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
player_crash(gameobject arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret83) ;
// ATStmpdec_void(tmp84) ;
ATStmpdec(tmp85, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3352(line=151, offs=11) -- 3538(line=158, offs=4)
*/
ATSINSflab(__patsflab_player_crash):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3374(line=151, offs=33) -- 3538(line=158, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3389(line=152, offs=11) -- 3407(line=152, offs=29)
*/
ATSINSmove_void(tmp84, enemy_remove(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3422(line=153, offs=13) -- 3434(line=153, offs=25)
*/
ATSINSmove(tmp85, _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_sats__player_get()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3442(line=155, offs=3) -- 3533(line=157, offs=18)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3459(line=156, offs=5) -- 3465(line=156, offs=11)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3422(line=153, offs=13) -- 3434(line=153, offs=25)
*/
ATSifthen(ATSCKptriscons(tmp85)) { ATSINSgoto(__atstmplab7) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3465(line=156, offs=11) -- 3465(line=156, offs=11)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3469(line=156, offs=15) -- 3471(line=156, offs=17)
*/
ATSINSmove_void(tmpret83, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3520(line=157, offs=5) -- 3526(line=157, offs=11)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3422(line=153, offs=13) -- 3434(line=153, offs=25)
*/
ATSifthen(ATSCKptrisnull(tmp85)) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3442(line=155, offs=3) -- 3533(line=157, offs=18)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3526(line=157, offs=11) -- 3526(line=157, offs=11)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3531(line=157, offs=16) -- 3533(line=157, offs=18)
*/
ATSINSmove_void(tmpret83, ATSPMVempty()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3374(line=151, offs=33) -- 3538(line=158, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret83) ;
} /* end of [player_crash] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3562(line=160, offs=21) -- 4177(line=178, offs=4)
*/
/*
local: 
global: enemy_move$12$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
enemy_move(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2, atstype_cloptr arg3)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret86) ;
ATStmpdec(tmp87, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp88, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp89, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp90, atstkind_t0ype(atstype_double)) ;
// ATStmpdec_void(tmp91) ;
ATStmpdec(tmp92, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp93, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3552(line=160, offs=11) -- 4177(line=178, offs=4)
*/
ATSINSflab(__patsflab_enemy_move):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3595(line=161, offs=1) -- 4177(line=178, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3616(line=162, offs=17) -- 3641(line=162, offs=42)
*/
ATSINSmove(tmp87, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3660(line=163, offs=17) -- 3685(line=163, offs=42)
*/
ATSINSmove(tmp88, enemy_getPosition_Y(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3704(line=164, offs=17) -- 3721(line=164, offs=34)
*/
ATSINSmove(tmp89, ats2jspre_add_double_double(tmp87, arg1)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3739(line=165, offs=17) -- 3756(line=165, offs=34)
*/
ATSINSmove(tmp90, ats2jspre_add_double_double(tmp88, arg2)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3769(line=166, offs=12) -- 3811(line=166, offs=54)
*/
ATSINSmove_void(tmp91, enemy_setPosition(arg0, tmp89, tmp90)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3827(line=167, offs=15) -- 3869(line=167, offs=57)
*/
ATSINSmove(tmp92, enemy_check_crash(arg0, tmp89, tmp90)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3877(line=169, offs=3) -- 4172(line=177, offs=6)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3897(line=170, offs=5) -- 3898(line=170, offs=6)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3827(line=167, offs=15) -- 3869(line=167, offs=57)
*/
ATSifnthen(ATSCKpat_int(tmp92, ATSPMVint(1))) { ATSINSgoto(__atstmplab10) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3898(line=170, offs=6) -- 3898(line=170, offs=6)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3902(line=170, offs=10) -- 3905(line=170, offs=13)
*/
ATSINSmove_void(tmpret86, ATSfunclo_clo(arg3, (atstype_cloptr), atsvoid_t0ype)(arg3)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3918(line=171, offs=5) -- 3919(line=171, offs=6)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3827(line=167, offs=15) -- 3869(line=167, offs=57)
*/
ATSifnthen(ATSCKpat_int(tmp92, ATSPMVint(0))) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3877(line=169, offs=3) -- 4172(line=177, offs=6)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3919(line=171, offs=6) -- 3919(line=171, offs=6)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3923(line=171, offs=10) -- 4172(line=177, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3962(line=172, offs=23) -- 4004(line=172, offs=65)
*/
ATSINSmove(tmp93, enemy_check_bound(arg0, tmp89, tmp90)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4016(line=174, offs=5) -- 4160(line=176, offs=86)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4044(line=175, offs=7) -- 4045(line=175, offs=8)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3962(line=172, offs=23) -- 4004(line=172, offs=65)
*/
ATSifnthen(ATSCKpat_int(tmp93, ATSPMVint(1))) { ATSINSgoto(__atstmplab14) ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4045(line=175, offs=8) -- 4045(line=175, offs=8)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4049(line=175, offs=12) -- 4067(line=175, offs=30)
*/
ATSINSmove_void(tmpret86, enemy_remove(arg0)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4081(line=176, offs=7) -- 4082(line=176, offs=8)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3962(line=172, offs=23) -- 4004(line=172, offs=65)
*/
ATSifnthen(ATSCKpat_int(tmp93, ATSPMVint(0))) { ATSINScaseof_fail("/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4016(line=174, offs=5) -- 4160(line=176, offs=86)") ; } ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4082(line=176, offs=8) -- 4082(line=176, offs=8)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4086(line=176, offs=12) -- 4160(line=176, offs=86)
*/
ATSINSmove_void(tmpret86, setTimeout_cloref(ATSPMVcfunlab(-1, __patsfun_13, (arg0, arg1, arg2, arg3)), ATSPMVf0loat(20.0))) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3923(line=171, offs=10) -- 4172(line=177, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 3595(line=161, offs=1) -- 4177(line=178, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret86) ;
} /* end of [enemy_move] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4104(line=176, offs=30) -- 4153(line=176, offs=79)
*/
/*
local: 
global: __patsfun_13$0(level=1)
local: enemy$197(1)(HSEcst(gameobject)), speed_x$198(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), speed_y$199(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), k$200(1)(HSEfun(; HSEcst(atsvoid_t0ype)))
global: enemy$197(1)(HSEcst(gameobject)), speed_x$198(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), speed_y$199(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_double)))), k$200(1)(HSEfun(; HSEcst(atsvoid_t0ype)))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_13(gameobject env0, atstkind_t0ype(atstype_double) env1, atstkind_t0ype(atstype_double) env2, atstype_funptr env3)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret94) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4104(line=176, offs=30) -- 4153(line=176, offs=79)
*/
ATSINSflab(__patsflab___patsfun_13):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4114(line=176, offs=40) -- 4152(line=176, offs=78)
*/
ATSINSmove_void(tmpret94, enemy_move(env0, env1, env2, env3)) ;

ATSfunbody_end()
ATSreturn_void(tmpret94) ;
} /* end of [__patsfun_13] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4208(line=180, offs=28) -- 4805(line=194, offs=4)
*/
/*
local: 
global: enemy_check_crash$14$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_crash(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret95, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp96, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp97, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp98, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp99, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp100, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp101, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp102, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp103, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp104) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4191(line=180, offs=11) -- 4805(line=194, offs=4)
*/
ATSINSflab(__patsflab_enemy_check_crash):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4236(line=180, offs=56) -- 4805(line=194, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4258(line=181, offs=18) -- 4280(line=181, offs=40)
*/
ATSINSmove(tmp96, player_getPosition_X()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4299(line=182, offs=18) -- 4321(line=182, offs=40)
*/
ATSINSmove(tmp97, player_getPosition_Y()) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4339(line=183, offs=17) -- 4364(line=183, offs=42)
*/
ATSINSmove(tmp98, enemy_getPosition_X(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4383(line=184, offs=17) -- 4408(line=184, offs=42)
*/
ATSINSmove(tmp99, enemy_getPosition_Y(arg0)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4424(line=185, offs=14) -- 4471(line=185, offs=61)
*/
ATSINSmove(tmp100, calc_dist(tmp96, tmp97, tmp98, tmp99)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4585(line=186, offs=20) -- 4611(line=186, offs=46)
*/
ATSINSmove(tmp102, ats2jspre_add_double_double(ATSPMVfloat(18.000000000000000000), ATSPMVfloat(18.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4584(line=186, offs=19) -- 4618(line=186, offs=53)
*/
ATSINSmove(tmp101, ats2jspre_div_double_double(tmp102, ATSPMVf0loat(2.0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4686(line=189, offs=6) -- 4702(line=189, offs=22)
*/
ATSINSmove(tmp103, ats2jspre_lt_double_double(tmp100, tmp101)) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4683(line=189, offs=3) -- 4800(line=193, offs=13)
*/
ATSif(
tmp103
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4708(line=189, offs=28) -- 4793(line=193, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4725(line=190, offs=13) -- 4775(line=190, offs=63)
*/
ATSINSmove_void(tmp104, crash_report(tmp96, tmp97, tmp98, tmp99)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4785(line=192, offs=3) -- 4786(line=192, offs=4)
*/
ATSINSmove(tmpret95, ATSPMVi0nt(1)) ;
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4708(line=189, offs=28) -- 4793(line=193, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4799(line=193, offs=12) -- 4800(line=193, offs=13)
*/
ATSINSmove(tmpret95, ATSPMVi0nt(0)) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4236(line=180, offs=56) -- 4805(line=194, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret95) ;
} /* end of [enemy_check_crash] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4836(line=196, offs=28) -- 4971(line=198, offs=9)
*/
/*
local: 
global: enemy_check_bound$15$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
enemy_check_bound(gameobject arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret105, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp106, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp107, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp108, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp109, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4819(line=196, offs=11) -- 4971(line=198, offs=9)
*/
ATSINSflab(__patsflab_enemy_check_bound):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSINSmove(tmp109, ats2jspre_gt_double_double(arg1, ATSPMVfloat(400.000000000000000000))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSif(
tmp109
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSINSmove(tmp108, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSINSmove(tmp108, ats2jspre_lt_double_double(arg1, ATSPMVf0loat(0.0))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSif(
tmp108
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSINSmove(tmp107, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSINSmove(tmp107, ats2jspre_gt_double_double(arg2, ATSPMVfloat(500.000000000000000000))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSif(
tmp107
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSINSmove(tmp106, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4871(line=197, offs=6) -- 4954(line=197, offs=89)
*/
ATSINSmove(tmp106, ats2jspre_lt_double_double(arg2, ATSPMVf0loat(0.0))) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4868(line=197, offs=3) -- 4971(line=198, offs=9)
*/
ATSif(
tmp106
) ATSthen() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4960(line=197, offs=95) -- 4961(line=197, offs=96)
*/
ATSINSmove(tmpret105, ATSPMVi0nt(1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 4970(line=198, offs=8) -- 4971(line=198, offs=9)
*/
ATSINSmove(tmpret105, ATSPMVi0nt(0)) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret105) ;
} /* end of [enemy_check_bound] */

/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 5087(line=208, offs=21) -- 5104(line=208, offs=38)
*/
/*
local: 
global: cloref_app$16$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
cloref_app(atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret110) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 5077(line=208, offs=11) -- 5104(line=208, offs=38)
*/
ATSINSflab(__patsflab_cloref_app):
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 5097(line=208, offs=31) -- 5104(line=208, offs=38)
*/
ATSINSmove_void(tmpret110, ATSfunclo_clo(arg0, (atstype_cloptr), atsvoid_t0ype)(arg0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret110) ;
} /* end of [cloref_app] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 359(line=23, offs=16) -- 370(line=23, offs=27)
*/
ATSINSmove(statmp0, ats2jspre_ref(ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 395(line=24, offs=24) -- 406(line=24, offs=35)
*/
ATSINSmove(statmp1, ats2jspre_ref(ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 427(line=25, offs=20) -- 446(line=25, offs=39)
*/
ATSINSmove(statmp2, ats2jspre_ref(ATSPMVintrep(100))) ;

/*
emit_instr: loc0 = /home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 464(line=26, offs=16) -- 476(line=26, offs=28)
*/
ATSINSmove(statmp3, ats2jspre_ref(ATSPMVi0nt(10))) ;

/* (*nothing*) */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
ATSextern()
atsvoid_t0ype
my_dynload()
{
ATSfunbody_beg()
ATSINSmove_void(tmpret_void, _057_home_057_grad3_057_gladius_057_CS520_057_hwtest_057_SpaceInvaders_057_myGame_056_dats__dynload()) ;
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} // end-of-dynload-alias
/*
/home/grad3/gladius/CS520/hwtest/SpaceInvaders/myGame.dats: 5108(line=210, offs=1) -- 5531(line=233, offs=3)
*/
ATSextcode_beg()
function
ATS_start()
{
  var _ = my_dynload();
  var _ = init();
}

function
test(x, y, z, a){
  console.log("player:" + x + ", " + y + "; enemy:" + z + ", " + a);
}

function
crash_report(x, y, z, a){
  console.log("crash found => player:" + x + ", " + y + "; enemy:" + z + ", " + a);
}

function
setTimeout_cloref(fwork, ntime)
{
  setTimeout(function(){cloref_app(fwork);return;}, ntime);
}
ATSextcode_end()

/* ****** ****** */

/* end-of-compilation-unit */
